"""Direct SQLite insert — no Flask imports, no zoho_mail, no dotenv overhead"""
import sqlite3, os
from datetime import datetime

DB = r"C:\Users\Kishan\BIM_CRM\bim_crm.db"

conn = sqlite3.connect(DB, timeout=15)
conn.execute("PRAGMA journal_mode=WAL")
conn.execute("PRAGMA busy_timeout=5000")

leads = [
# ── Template A — GC / Engineering ─────────────────────────────────────────────
("Karl","Almstead","k.almstead@turnerconstruction.com","Turner Construction","VDC Director","","turnerconstruction.com","New York","USA","General Contractor","New",95,"VDC, BIM Coordination, Clash Detection","High","BIM outsourcing during project peak","A","","","Manages all VDC operations across USA"),
("Jennifer","Rice","j.rice@turnerconstruction.com","Turner Construction","BIM Manager","","turnerconstruction.com","New York","USA","General Contractor","New",90,"Revit Modelling, Clash Detection","High","BIM capacity during peak phases","A","","","BIM standards and delivery"),
("Mark","Layman","m.layman@turnerconstruction.com","Turner Construction","Technology Director","","turnerconstruction.com","New York","USA","General Contractor","New",88,"BIM Automation, Dynamo Scripts","High","BIM automation and workflow efficiency","A","","","Digital transformation and BIM tech stack"),
("Troy","Rudd","troy.rudd@aecom.com","AECOM","CEO","","aecom.com","Dallas, TX","USA","Engineering / Infrastructure","New",95,"BIM, Scan-to-BIM, 4D Scheduling","High","BIM outsourcing for infrastructure projects","A","","","Global infrastructure firm, peak BIM demand"),
("Lara","Washington","l.washington@aecom.com","AECOM","Digital Delivery Director","","aecom.com","Los Angeles, CA","USA","Engineering / Infrastructure","New",92,"BIM Coordination, Revit, Digital Twin","High","BIM capacity overflow","A","","","BIM and digital delivery lead"),
("James","Simmons","j.simmons@aecom.com","AECOM","BIM Manager","","aecom.com","New York, NY","USA","Engineering / Infrastructure","New",88,"Revit Modelling, MEP Coordination","High","BIM outsourcing support","A","","","Day-to-day BIM delivery on projects"),
("Carey","Smith","c.smith@parsons.com","Parsons Corporation","CEO","","parsons.com","Centreville, VA","USA","Engineering / Defence / Infrastructure","New",95,"BIM Modelling, 4D/5D, Dynamo Automation","High","BIM outsourcing for mega infrastructure","A","","","110km Floating Tunnel BIM capacity needed"),
("David","Zelinskas","d.zelinskas@parsons.com","Parsons Corporation","VDC Manager","","parsons.com","Centreville, VA","USA","Engineering / Defence / Infrastructure","New",92,"Revit Modelling, Dynamo, BIM Coordination","High","BIM automation and coordination support","A","","","VDC lead on large infrastructure projects"),
("Rachel","Torres","r.torres@parsons.com","Parsons Corporation","BIM Lead","","parsons.com","Los Angeles, CA","USA","Engineering / Defence / Infrastructure","New",88,"Revit, BIM 360, Coordination","High","BIM capacity outsourcing","A","","","BIM delivery on tunnels and transport infra"),
("Steve","Demetriou","s.demetriou@jacobs.com","Jacobs Engineering","CEO","","jacobs.com","Dallas, TX","USA","Engineering / Consulting","New",90,"BIM Modelling, 4D Scheduling, Scan-to-BIM","High","BIM capacity for large infrastructure","A","","","Global engineering firm needing BIM support"),
("Patrick","Hill","p.hill@jacobs.com","Jacobs Engineering","Director of Digital Delivery","","jacobs.com","Dallas, TX","USA","Engineering / Consulting","New",88,"BIM Coordination, Revit, Dynamo","High","BIM capacity and automation","A","","","Leads BIM/digital delivery across projects"),
("Megan","Fuller","m.fuller@jacobs.com","Jacobs Engineering","BIM Coordinator","","jacobs.com","Dallas, TX","USA","Engineering / Consulting","New",82,"Revit MEP, Clash Detection, Coordination","High","BIM outsourcing during crunch","A","","","BIM coordination on infrastructure projects"),
("Richard","Kennedy","r.kennedy@skanska.com","Skanska USA","CEO","","usa.skanska.com","New York, NY","USA","General Contractor","New",92,"BIM Coordination, Clash Detection, 4D","High","BIM outsourcing for large GC","A","","","Large GC with peak BIM capacity issues"),
("Mike","Woelfel","m.woelfel@skanska.com","Skanska USA","VDC Director","","usa.skanska.com","New York, NY","USA","General Contractor","New",90,"Revit, BIM 360, Clash Detection","High","BIM coordination during construction phase","A","","","VDC coordination across Skanska US projects"),
("Amy","Randolph","a.randolph@skanska.com","Skanska USA","BIM Manager","","usa.skanska.com","Chicago, IL","USA","General Contractor","New",85,"MEP Coordination, LOD 400, Clash Detection","High","BIM outsourcing during project peaks","A","","","BIM standards and coordination across projects"),
("Alexandre","Lheureux","a.lheureux@wsp.com","WSP Global","CEO","","wsp.com","Montreal, QC","Canada","Engineering / Consulting","New",92,"BIM Modelling, Scan-to-BIM, Digital Twin","High","BIM outsourcing for global engineering firm","A","","","Global engineering firm with peak BIM demand"),
("Nathalie","Dupuis","n.dupuis@wsp.com","WSP Global","Director of BIM","","wsp.com","Toronto, ON","Canada","Engineering / Consulting","New",90,"BIM Coordination, Revit, 4D Scheduling","High","BIM capacity overflow for Canadian projects","A","","","BIM strategy and delivery for Canada region"),
("Chris","Bergeron","c.bergeron@wsp.com","WSP Global","BIM Coordinator","","wsp.com","Vancouver, BC","Canada","Engineering / Consulting","New",82,"Revit MEP, Clash Detection, BIM 360","High","BIM coordination support","A","","","BIM coordination on western Canada projects"),
("Tony","Lombardo","info.aus@lendlease.com","Lendlease","CEO","","lendlease.com","Sydney, NSW","Australia","General Contractor / Developer","New",92,"BIM Coordination, Scan-to-BIM, LOD 400","High","BIM outsourcing for Australian developer/GC","A","","","Major Australian GC with complex BIM needs"),
("Dale","Connor","d.connor@lendlease.com","Lendlease","Digital Construction Director","","lendlease.com","Sydney, NSW","Australia","General Contractor / Developer","New",90,"BIM, 4D Scheduling, Digital Delivery","High","BIM outsourcing for large mixed-use projects","A","","","Digital construction strategy and BIM delivery"),
("Karen","Ho","k.ho@lendlease.com","Lendlease","BIM Manager","","lendlease.com","Melbourne, VIC","Australia","General Contractor / Developer","New",85,"Revit, BIM 360, Clash Detection","High","BIM support during design-to-construction","A","","","BIM coordination on major Australian projects"),
("Gregory","Hodkinson","g.hodkinson@arup.com","Arup","Chairman","","arup.com","London","UK","Engineering / Consulting","New",92,"BIM Coordination, Scan-to-BIM, Digital Twin","High","BIM outsourcing for global engineering firm","A","","","World-leading engineering consultancy"),
("Dervilla","Mitchell","d.mitchell@arup.com","Arup","Digital Practice Lead","","arup.com","London","UK","Engineering / Consulting","New",90,"BIM, Digital Twin, Scan-to-BIM","High","BIM capacity and digital twin outsourcing","A","","","Leads digital and BIM practice at Arup"),
("Tom","Sheridan","t.sheridan@arup.com","Arup","BIM Lead","","arup.com","Dublin","UK","Engineering / Consulting","New",85,"Revit, BIM Coordination, MEP","High","BIM outsourcing support","A","","","BIM delivery on infrastructure projects"),
("Ray","ORourke","info@laingorourke.com","Laing ORourke","Chairman","","laingorourke.com","London","UK","General Contractor","New",92,"BIM Coordination, LOD 500, 4D Scheduling","High","BIM outsourcing for large UK GC","A","","","Major UK GC with complex BIM requirements"),
("James","Pellatt","j.pellatt@laingorourke.com","Laing ORourke","Digital Engineering Director","","laingorourke.com","London","UK","General Contractor","New",90,"BIM, Digital Engineering, Clash Detection","High","Digital BIM outsourcing","A","","","Digital engineering strategy across projects"),
("Sarah","Marshall","s.marshall@laingorourke.com","Laing ORourke","BIM Manager","","laingorourke.com","London","UK","General Contractor","New",85,"Revit, NBS, BIM Coordination","High","BIM capacity overflow","A","","","BIM coordination and delivery on UK projects"),
("James","Harris","info@mottmac.com","Mott MacDonald","Group CEO","","mottmac.com","Croydon","UK","Engineering / Consulting","New",90,"BIM, Scan-to-BIM, 4D Scheduling","High","BIM outsourcing for global consulting firm","A","","","Global engineering and management consultancy"),
("Kevin","Harrington","k.harrington@mottmac.com","Mott MacDonald","Digital Engineering Director","","mottmac.com","Croydon","UK","Engineering / Consulting","New",88,"BIM Coordination, Digital Delivery, Revit","High","BIM capacity support","A","","","Digital engineering and BIM lead"),
("Juan","Larrainzar","info@hochtief.de","Hochtief","CEO","","hochtief.de","Essen","Germany","General Contractor","New",90,"BIM Coordination, LOD 400, Scan-to-BIM","High","BIM outsourcing for large German GC","A","","","Major German GC with global project BIM needs"),
("Martin","Schmitt","m.schmitt@hochtief.de","Hochtief","BIM Director","","hochtief.de","Essen","Germany","General Contractor","New",88,"BIM Coordination, Revit, 4D Scheduling","High","BIM capacity overflow","A","","","BIM strategy and delivery for Hochtief Germany"),
("Klaus","Wagner","k.wagner@hochtief.de","Hochtief","VDC Manager","","hochtief.de","Munich","Germany","General Contractor","New",82,"Revit MEP, Clash Detection, BIM Coordination","High","BIM outsourcing during project peaks","A","","","VDC coordination on German infrastructure projects"),
("Thomas","Birtel","info@strabag.com","Strabag","CEO","","strabag.com","Vienna","Germany","General Contractor","New",88,"BIM Modelling, 4D Scheduling, Scan-to-BIM","High","BIM outsourcing for pan-European GC","A","","","Major European GC needing BIM offshore support"),
("Hans","Kirchner","h.kirchner@strabag.com","Strabag","Digital Construction Director","","strabag.com","Vienna","Germany","General Contractor","New",85,"BIM Coordination, Revit, Digital Twin","High","BIM capacity during peak construction","A","","","Digital construction strategy at Strabag"),
# ── Template B — Architecture ──────────────────────────────────────────────────
("Andy","Cohen","info@gensler.com","Gensler","Co-CEO","","gensler.com","San Francisco, CA","USA","Architecture","New",92,"Revit CD Documentation, BIM Coordination","High","Revit CD outsourcing during design peaks","B","","","Worlds largest architecture firm BIM overflow"),
("Chris","Farmer","c.farmer@gensler.com","Gensler","BIM Director","","gensler.com","New York, NY","USA","Architecture","New",92,"Revit Families, BIM Standards, CD Documentation","High","Revit family creation and CD outsourcing","B","","","BIM standards across all Gensler studios"),
("Tom","Ito","t.ito@gensler.com","Gensler","Technology Director","","gensler.com","Los Angeles, CA","USA","Architecture","New",88,"Revit, Dynamo, BIM Automation","High","BIM automation and workflow scripts","B","","","Technology and BIM automation across studios"),
("Bill","Hellmuth","info@hok.com","HOK","President","","hok.com","Washington, DC","USA","Architecture","New",88,"Revit Documentation, BIM Coordination","High","Revit CD outsourcing for major projects","B","","","Leading US architecture firm CD crunch phases"),
("Adam","Trott","a.trott@hok.com","HOK","Director of BIM","","hok.com","New York, NY","USA","Architecture","New",88,"Revit Families, BIM Standards, CD Documentation","High","Revit outsourcing during DD/CD phases","B","","","BIM lead across HOK project studios"),
("Laura","Ettelman","l.ettelman@hok.com","HOK","Project Architect","","hok.com","St. Louis, MO","USA","Architecture","New",80,"Revit Documentation, Sections, Elevations","High","CD documentation outsourcing","B","","","Project architect managing CD deliverables"),
("Phil","Harrison","info@perkinswill.com","Perkins+Will","CEO","","perkinswill.com","Atlanta, GA","USA","Architecture","New",88,"Revit Modelling, BIM Coordination, Scan-to-BIM","High","Revit CD outsourcing for large architecture firm","B","","","Major US architecture firm with peak Revit demand"),
("Kevin","Pendergast","k.pendergast@perkinswill.com","Perkins+Will","BIM Manager","","perkinswill.com","New York, NY","USA","Architecture","New",85,"Revit, BIM Standards, CD Documentation","High","CD documentation overflow","B","","","BIM manager for New York studio"),
("Norman","Foster","info@fosterandpartners.com","Foster and Partners","Founder","","fosterandpartners.com","London","UK","Architecture","New",90,"Revit Modelling, BIM Coordination, Scan-to-BIM","High","Revit CD outsourcing for iconic architecture","B","","","World-renowned architecture firm BIM overflow"),
("Tom","Coward","t.coward@fosterandpartners.com","Foster and Partners","BIM Lead","","fosterandpartners.com","London","UK","Architecture","New",85,"Revit, Grasshopper, BIM Coordination","High","Parametric Revit and BIM coordination","B","","","BIM standards and delivery on major projects"),
("Patrik","Schumacher","info@zaha-hadid.com","Zaha Hadid Architects","Principal","","zaha-hadid.com","London","UK","Architecture","New",88,"Revit, Parametric Modelling, BIM Coordination","High","Revit BIM outsourcing for complex geometry","B","","","Iconic architecture firm with complex BIM needs"),
("Jim","Heverin","j.heverin@zaha-hadid.com","Zaha Hadid Architects","Director","","zaha-hadid.com","London","UK","Architecture","New",85,"Revit Modelling, BIM Coordination","High","Complex geometry Revit outsourcing","B","","","Project director on major ZHA commissions"),
("Bjarke","Ingels","info@big.dk","BIG Bjarke Ingels Group","Founder","","big.dk","Copenhagen","Germany","Architecture","New",88,"Revit Modelling, BIM Coordination","High","Revit outsourcing for high-profile global projects","B","","","World-leading architecture studio with BIM overflow"),
("Andreas","Pedersen","a.pedersen@big.dk","BIG Bjarke Ingels Group","Partner","","big.dk","Copenhagen","Germany","Architecture","New",85,"Revit, Grasshopper, BIM Coordination","High","BIM and parametric modelling outsourcing","B","","","Partner managing European projects"),
("Craig","Allardice","info@woodsbagot.com","Woods Bagot","Global CEO","","woodsbagot.com","Melbourne, VIC","Australia","Architecture","New",85,"Revit CD Documentation, BIM Coordination","High","Revit outsourcing for Australian architecture firm","B","","","Leading Australian architecture firm CD overflow"),
("Daniel","Goldberg","d.goldberg@woodsbagot.com","Woods Bagot","BIM Manager","","woodsbagot.com","Sydney, NSW","Australia","Architecture","New",82,"Revit Modelling, Families, CD Documentation","High","CD documentation outsourcing","B","","","BIM manager for Sydney and Melbourne studios"),
# ── Template C — Drone / Scan-to-BIM ──────────────────────────────────────────
("David","Henley","info@archaerial.com","Arch Aerial","CEO","","archaerial.com","Houston, TX","USA","Drone Survey / Infrastructure","New",85,"Scan-to-BIM, LiDAR Processing, Point Cloud to Revit","High","Convert drone data to BIM","C","","","Energy and infrastructure drone survey needs BIM output"),
("Scott","Howe","s.howe@archaerial.com","Arch Aerial","Operations Director","","archaerial.com","Houston, TX","USA","Drone Survey / Infrastructure","New",82,"Scan-to-BIM, LiDAR Point Cloud","High","LiDAR to BIM workflow","C","","","Operations lead manages survey to deliverable pipeline"),
("Ryan","Nilsson","r.nilsson@darlingltd.com","Darling Geomatics","Director","","darlingltd.com","Denver, CO","USA","Drone Survey / BIM / LiDAR","New",90,"Scan-to-BIM, LiDAR Modelling, BIM Coordination","High","Scan-to-BIM workflow partner","C","","","LiDAR and drone survey BIM conversion bottleneck"),
("Maria","Castillo","m.castillo@darlingltd.com","Darling Geomatics","Survey Manager","","darlingltd.com","Denver, CO","USA","Drone Survey / BIM / LiDAR","New",85,"Scan-to-BIM, Point Cloud Registration","High","Point cloud to Revit pipeline","C","","","Survey manager needing BIM output for clients"),
("Jake","Morrison","j.morrison@darlingltd.com","Darling Geomatics","BIM Technician","","darlingltd.com","Denver, CO","USA","Drone Survey / BIM / LiDAR","New",78,"Revit Modelling from Point Cloud","High","Revit modelling from LiDAR data","C","","","BIM technician converting scan data to Revit"),
("Ian","Tansey","info@prodroneworx.co.uk","ProDroneWorx","Managing Director","+44 7805 864642","prodroneworx.co.uk","Beaconsfield","UK","Drone Survey / BIM / Inspection","New",88,"Scan-to-BIM, LiDAR Modelling, BIM Coordination","High","Scan-to-BIM workflow partner","C","linkedin.com/in/ian-tansey-a0593513","","Leading UK drone BIM firm capacity constrained"),
("Phil","Carter","p.carter@prodroneworx.co.uk","ProDroneWorx","BIM Lead","","prodroneworx.co.uk","Beaconsfield","UK","Drone Survey / BIM / Inspection","New",85,"Revit from Point Cloud, LOD 300-400","High","Revit modelling outsourcing","C","","","BIM lead needing overflow capacity"),
("Chris","Fleming","info@thecyberhawk.com","Cyberhawk","CEO","","thecyberhawk.com","Livingston","UK","Drone Inspection / Industrial","New",85,"Scan-to-BIM from inspection data, As-built BIM","High","Inspection data to BIM conversion","C","linkedin.com/company/cyberhawk","","Industrial inspection drone clients need asset BIM"),
("Jonathan","Lee","j.lee@thecyberhawk.com","Cyberhawk","Technical Director","","thecyberhawk.com","Livingston","UK","Drone Inspection / Industrial","New",82,"BIM from drone inspection, LOD 300","High","As-built BIM from inspection data","C","","","Technical lead managing inspection data pipeline"),
("Aaron","Iles","info@uavisuals.com","UAVISUALS","Founder","1300711965","uavisuals.com","Melbourne, VIC","Australia","Drone Services / LiDAR","New",80,"Scan-to-BIM, LiDAR Modelling","High","Scan-to-BIM workflow partner","C","","","No in-house BIM team for scan-to-BIM conversion"),
("Warren","Priestly","info@remsense.com.au","RemSense","CEO","","remsense.com.au","Perth, WA","Australia","Drone / Digital Twin / UAV","New",82,"Scan-to-BIM, Digital Twin BIM","High","Digital twin BIM from drone data","C","","","Digital twin projects need BIM deliverables"),
("Jason","Briggs","j.briggs@remsense.com.au","RemSense","Digital Twin Manager","","remsense.com.au","Perth, WA","Australia","Drone / Digital Twin / UAV","New",80,"Revit from LiDAR, As-built Documentation","High","BIM for digital twin projects","C","","","Digital twin delivery needs BIM modelling partner"),
("Thomas","deBruin","info@ddc.works","Dutch Drone Company","CEO","","ddc.works","Amsterdam","Netherlands","Drone Survey / UAV","New",80,"Scan-to-BIM, LiDAR Point Cloud","High","Scan-to-BIM workflow partner","C","","","European drone survey needs BIM conversion partner"),
("Mathieu","Moreau","contact@altametris.com","Altametris","CEO","","altametris.com","Paris","France","Drone Survey / Rail / Infrastructure","New",82,"Scan-to-BIM, LiDAR Modelling, Rail BIM","High","Rail and infra drone data to BIM","C","","","Rail and infra drone survey BIM conversion needed"),
("Rabih","BouRashid","info@aerodronics.ae","Aerodronics","CEO","","aerodronics.ae","Dubai","UAE","Drone Survey / Inspection / Smart City","New",82,"Scan-to-BIM, LiDAR, Smart City BIM","High","Smart city drone data to BIM","C","","","UAE smart city and construction drone needs BIM"),
("Hany","Fares","info@falcon-eye.ae","Falcon Eye Drones","CEO","","falcon-eye.ae","Abu Dhabi","UAE","Drone Survey / Infrastructure","New",80,"Scan-to-BIM, Progress Monitoring, LiDAR","High","Drone data to BIM for Abu Dhabi projects","C","","","Abu Dhabi infra projects need BIM from drone surveys"),
# ── Template D — INFRA X India ─────────────────────────────────────────────────
("Brijesh","Pandey","brijesh@garudauav.com","GarudaUAV","Founder & CEO","","garudauav.com","Noida, UP","India","Drone Survey / UAV / AI","New",90,"INFRA X Site Monitoring, Scan-to-BIM","High","INFRA X Drone Progress Monitoring","D","","","Large infra clients need single-dashboard site visibility"),
("Himanshu","Singh","himanshu@garudauav.com","GarudaUAV","Operations Executive","","garudauav.com","Noida, UP","India","Drone Survey / UAV","New",82,"INFRA X, Resource Allocation Tracking","High","INFRA X for infra project monitoring","D","","","Operations lead managing drone survey delivery"),
("Priya","Mehta","p.mehta@garudauav.com","GarudaUAV","Business Development Manager","","garudauav.com","Noida, UP","India","Drone Survey / UAV","New",78,"INFRA X Partnership, Joint Bid","High","INFRA X collaboration opportunity","D","","","BD looking for tech partners for infra projects"),
("Ranjit","Singh","info@igdrones.com","IG Drones","CEO","","igdrones.com","Gurugram, Haryana","India","Drone Survey / GIS / Mapping","New",85,"INFRA X Site Monitoring, Compare View","High","INFRA X Drone Progress Monitoring","D","","","Infrastructure clients want one-desk site visibility"),
("Abhishek","Kumar","a.kumar@igdrones.com","IG Drones","Technical Director","","igdrones.com","Gurugram, Haryana","India","Drone Survey / GIS","New",82,"INFRA X, Automated Reports, Progress Monitoring","High","INFRA X technology partnership","D","","","Technical lead on GIS and drone survey projects"),
("Neha","Sharma","n.sharma@igdrones.com","IG Drones","Project Manager","","igdrones.com","Gurugram, Haryana","India","Drone Survey / GIS","New",75,"INFRA X Site Reports, Resource Tracking","High","Automated progress reports for clients","D","","","PM managing delivery on infrastructure drone projects"),
("Ankit","Kumar","ankit@skylarkdrones.com","Skylark Drones","CEO","","skylarkdrones.com","Bangalore","India","Drone Survey / Mining / Infra","New",88,"INFRA X, Resource Allocation, Reports","High","INFRA X Drone Progress Monitoring","D","linkedin.com/company/skylark-drones","","Mining and infra projects lack real-time resource visibility"),
("Srikanth","Reddy","s.reddy@skylarkdrones.com","Skylark Drones","Operations Head","","skylarkdrones.com","Bangalore","India","Drone Survey / Mining / Infrastructure","New",85,"INFRA X Site Monitoring, Compare View","High","INFRA X site intelligence platform","D","","","Operations head managing multi-site drone deployments"),
("Kavya","Nair","k.nair@skylarkdrones.com","Skylark Drones","Business Development","","skylarkdrones.com","Bangalore","India","Drone Survey / Mining","New",78,"INFRA X Partnership","High","INFRA X collaboration for mining clients","D","","","BD for new mining and infra project opportunities"),
("Vipul","Kher","vipul@ideaforgedrones.com","IdeaForge","CEO","","ideaforgedrones.com","Mumbai","India","Drone Manufacturer / Services","New",85,"INFRA X Site Monitoring, Progress Reporting","High","INFRA X for infrastructure and defence clients","D","","","Large infra and defence clients need ground progress intelligence"),
("Rahul","Singh","r.singh@ideaforgedrones.com","IdeaForge","Sales Director","","ideaforgedrones.com","Mumbai","India","Drone Manufacturer / Services","New",80,"INFRA X, One-desk Monitoring","High","INFRA X as add-on service for clients","D","","","Sales director positioning INFRA X as premium offering"),
("Rajat","Kulshrestha","rajat@aarav-unmanned.com","Aarav Unmanned Systems","Co-Founder","","aarav-unmanned.com","Pune","India","Drone Survey / GIS","New",80,"INFRA X Site Monitoring","High","INFRA X Drone Progress Monitoring","D","","","Infrastructure monitoring gaps on large project sites"),
("Nitin","Gupta","n.gupta@aarav-unmanned.com","Aarav Unmanned Systems","Technical Lead","","aarav-unmanned.com","Pune","India","Drone Survey / GIS","New",75,"INFRA X, Automated Reports","High","INFRA X as tech platform for GIS clients","D","","","Technical lead on survey and mapping projects"),
("Gaurav","Srivastava","gaurav@garudsurvey.com","Garud Survey","CEO","","garudsurvey.com","Delhi","India","Drone Survey / Geospatial / Mining","New",88,"INFRA X Site Monitoring, Resource Allocation","High","INFRA X Drone Progress Monitoring","D","","","Mining and infra clients need real-time progress monitoring"),
("Deepak","Yadav","d.yadav@garudsurvey.com","Garud Survey","Operations Manager","","garudsurvey.com","Delhi","India","Drone Survey / Geospatial","New",80,"INFRA X, Compare View, Deviation Alerts","High","Automated site progress reports","D","","","Operations manager for large survey deployments"),
("Prashant","Chandak","prashant@equinoxsdrones.com","Equinox Drones","CEO","","equinoxsdrones.com","Hyderabad","India","Drone / UAV Inspection / Aerial","New",82,"INFRA X Compare View, Resource Allocation","High","INFRA X platform for multi-site monitoring","D","","","No single platform to monitor multiple sites simultaneously"),
("Suresh","Babu","s.babu@equinoxsdrones.com","Equinox Drones","Technical Director","","equinoxsdrones.com","Hyderabad","India","Drone / UAV Inspection","New",78,"INFRA X, One-desk Monitoring","High","INFRA X as premium service layer","D","","","Technical director on drone inspection projects"),
]

SQL = """
INSERT OR IGNORE INTO leads (
    first_name,last_name,email,company,title,phone,website,
    city,country,industry,status,priority_score,services_needed,
    outsourcing_likelihood,pitch_angle,email_template,linkedin_url,
    follow_up_stage,description,created_at,updated_at
) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
"""
now = datetime.utcnow().isoformat()
imported = 0
skipped  = 0
for row in leads:
    try:
        conn.execute(SQL, row + (now, now))
        imported += 1
    except sqlite3.IntegrityError:
        skipped += 1

conn.commit()
conn.close()

print(f"{'='*50}")
print(f"  Import complete")
print(f"  Imported : {imported}")
print(f"  Skipped  : {skipped} (duplicate emails)")
print(f"  Total    : {imported+skipped}")
print(f"{'='*50}")
