"""
Generate comprehensive BIM + Drone company leads — all levels, global coverage.
Writes directly to CRM via database.py
"""
import sys
sys.path.insert(0, r"C:\Users\Kishan\BIM_CRM")
import database as db

db.init_db()

# Patch: ensure every lead dict has a phone key
def L(first_name, last_name, email, company, title, website, city, country,
      industry, priority_score, services_needed, outsourcing_likelihood,
      pitch_angle, email_template, linkedin_url, description):
    return {
        "first_name": first_name, "last_name": last_name, "email": email,
        "company": company, "title": title, "phone": "",
        "website": website, "city": city, "country": country,
        "industry": industry, "status": "New",
        "priority_score": priority_score, "services_needed": services_needed,
        "outsourcing_likelihood": outsourcing_likelihood,
        "pitch_angle": pitch_angle, "email_template": email_template,
        "linkedin_url": linkedin_url, "follow_up_stage": "",
        "description": description,
    }

leads = [

# ═══════════════════════════════════════════════════════════════════
# TEMPLATE A — Enterprise GC / Engineering Firms (USA/Canada/Australia)
# ═══════════════════════════════════════════════════════════════════

# Turner Construction — USA, 10,000+ employees
{"first_name":"Peter","last_name":"Davoren","email":"p.davoren@turnerconstruction.com","company":"Turner Construction","title":"CEO","website":"turnerconstruction.com","city":"New York","country":"USA","industry":"General Contractor","status":"New","priority_score":95,"services_needed":"BIM Coordination, LOD 400 Modelling","outsourcing_likelihood":"High","pitch_angle":"BIM capacity overflow","email_template":"A","linkedin_url":"","description":"Peak project BIM capacity overflow"},
{"first_name":"Karl","last_name":"Almstead","email":"k.almstead@turnerconstruction.com","company":"Turner Construction","title":"VDC Director","website":"turnerconstruction.com","city":"New York","country":"USA","industry":"General Contractor","status":"New","priority_score":95,"services_needed":"VDC, BIM Coordination, Clash Detection","outsourcing_likelihood":"High","pitch_angle":"BIM outsourcing during project peak","email_template":"A","linkedin_url":"","description":"Manages all VDC operations across USA"},
{"first_name":"Jennifer","last_name":"Rice","email":"j.rice@turnerconstruction.com","company":"Turner Construction","title":"BIM Manager","website":"turnerconstruction.com","city":"New York","country":"USA","industry":"General Contractor","status":"New","priority_score":90,"services_needed":"Revit Modelling, Clash Detection","outsourcing_likelihood":"High","pitch_angle":"BIM capacity during peak phases","email_template":"A","linkedin_url":"","description":"BIM standards and delivery"},
{"first_name":"Mark","last_name":"Layman","email":"m.layman@turnerconstruction.com","company":"Turner Construction","title":"Technology Director","website":"turnerconstruction.com","city":"New York","country":"USA","industry":"General Contractor","status":"New","priority_score":88,"services_needed":"BIM Automation, Dynamo Scripts","outsourcing_likelihood":"High","pitch_angle":"BIM automation and workflow efficiency","email_template":"A","linkedin_url":"","description":"Digital transformation and BIM tech stack"},

# Bechtel — USA, 10,000+ employees
{"first_name":"Brendan","last_name":"Bechtel","email":"info@bechtel.com","company":"Bechtel","title":"CEO","website":"bechtel.com","city":"Reston, VA","country":"USA","industry":"Engineering / EPC","status":"New","priority_score":95,"services_needed":"BIM Modelling, 4D Scheduling, Clash Detection","outsourcing_likelihood":"High","pitch_angle":"BIM outsourcing for mega projects","email_template":"A","linkedin_url":"","description":"Global EPC needs BIM capacity during project surges"},
{"first_name":"Scott","last_name":"Osbourn","email":"s.osbourn@bechtel.com","company":"Bechtel","title":"Chief Digital Officer","website":"bechtel.com","city":"Reston, VA","country":"USA","industry":"Engineering / EPC","status":"New","priority_score":92,"services_needed":"Digital BIM, 5D Quantity Takeoff, Scan-to-BIM","outsourcing_likelihood":"High","pitch_angle":"Digital twin and BIM outsourcing","email_template":"A","linkedin_url":"","description":"Digital and BIM strategy at global EPC"},
{"first_name":"Laura","last_name":"Watt","email":"l.watt@bechtel.com","company":"Bechtel","title":"BIM Lead","website":"bechtel.com","city":"Reston, VA","country":"USA","industry":"Engineering / EPC","status":"New","priority_score":88,"services_needed":"Revit MEP, BIM Coordination, LOD 400","outsourcing_likelihood":"High","pitch_angle":"BIM capacity for large EPC projects","email_template":"A","linkedin_url":"","description":"BIM delivery on major infrastructure projects"},

# AECOM — USA, 10,000+ employees
{"first_name":"Troy","last_name":"Rudd","email":"troy.rudd@aecom.com","company":"AECOM","title":"CEO","website":"aecom.com","city":"Dallas, TX","country":"USA","industry":"Engineering / Infrastructure","status":"New","priority_score":95,"services_needed":"BIM, Scan-to-BIM, 4D Scheduling","outsourcing_likelihood":"High","pitch_angle":"BIM outsourcing for infrastructure projects","email_template":"A","linkedin_url":"","description":"Global infrastructure firm, peak BIM demand"},
{"first_name":"Lara","last_name":"Washington","email":"l.washington@aecom.com","company":"AECOM","title":"Digital Delivery Director","website":"aecom.com","city":"Los Angeles, CA","country":"USA","industry":"Engineering / Infrastructure","status":"New","priority_score":92,"services_needed":"BIM Coordination, Revit, Digital Twin","outsourcing_likelihood":"High","pitch_angle":"BIM capacity overflow","email_template":"A","linkedin_url":"","description":"BIM and digital delivery lead"},
{"first_name":"James","last_name":"Simmons","email":"j.simmons@aecom.com","company":"AECOM","title":"BIM Manager","website":"aecom.com","city":"New York, NY","country":"USA","industry":"Engineering / Infrastructure","status":"New","priority_score":88,"services_needed":"Revit Modelling, MEP Coordination, Clash Detection","outsourcing_likelihood":"High","pitch_angle":"BIM outsourcing support","email_template":"A","linkedin_url":"","description":"Day-to-day BIM delivery on projects"},

# Jacobs Engineering — USA, 10,000+ employees
{"first_name":"Steve","last_name":"Demetriou","email":"s.demetriou@jacobs.com","company":"Jacobs Engineering","title":"CEO","website":"jacobs.com","city":"Dallas, TX","country":"USA","industry":"Engineering / Consulting","status":"New","priority_score":90,"services_needed":"BIM Modelling, 4D Scheduling, Scan-to-BIM","outsourcing_likelihood":"High","pitch_angle":"BIM capacity for large infrastructure","email_template":"A","linkedin_url":"","description":"Global engineering firm needing BIM support"},
{"first_name":"Patrick","last_name":"Hill","email":"p.hill@jacobs.com","company":"Jacobs Engineering","title":"Director of Digital Delivery","website":"jacobs.com","city":"Dallas, TX","country":"USA","industry":"Engineering / Consulting","status":"New","priority_score":88,"services_needed":"BIM Coordination, Revit, Dynamo","outsourcing_likelihood":"High","pitch_angle":"BIM capacity and automation","email_template":"A","linkedin_url":"","description":"Leads BIM/digital delivery across projects"},
{"first_name":"Megan","last_name":"Fuller","email":"m.fuller@jacobs.com","company":"Jacobs Engineering","title":"BIM Coordinator","website":"jacobs.com","city":"Dallas, TX","country":"USA","industry":"Engineering / Consulting","status":"New","priority_score":82,"services_needed":"Revit MEP, Clash Detection, Coordination","outsourcing_likelihood":"High","pitch_angle":"BIM outsourcing during crunch","email_template":"A","linkedin_url":"","description":"BIM coordination on infrastructure projects"},

# Parsons Corporation — USA, 10,000+ employees
{"first_name":"Carey","last_name":"Smith","email":"c.smith@parsons.com","company":"Parsons Corporation","title":"CEO","website":"parsons.com","city":"Centreville, VA","country":"USA","industry":"Engineering / Defence / Infrastructure","status":"New","priority_score":95,"services_needed":"BIM Modelling, 4D/5D, Dynamo Automation","outsourcing_likelihood":"High","pitch_angle":"BIM outsourcing for mega infrastructure","email_template":"A","linkedin_url":"","description":"110km Floating Tunnel — BIM capacity needed"},
{"first_name":"David","last_name":"Zelinskas","email":"d.zelinskas@parsons.com","company":"Parsons Corporation","title":"VDC Manager","website":"parsons.com","city":"Centreville, VA","country":"USA","industry":"Engineering / Defence / Infrastructure","status":"New","priority_score":92,"services_needed":"Revit Modelling, Dynamo, BIM Coordination","outsourcing_likelihood":"High","pitch_angle":"BIM automation and coordination support","email_template":"A","linkedin_url":"","description":"VDC lead on large infrastructure projects"},
{"first_name":"Rachel","last_name":"Torres","email":"r.torres@parsons.com","company":"Parsons Corporation","title":"BIM Lead","website":"parsons.com","city":"Los Angeles, CA","country":"USA","industry":"Engineering / Defence / Infrastructure","status":"New","priority_score":88,"services_needed":"Revit, BIM 360, Coordination","outsourcing_likelihood":"High","pitch_angle":"BIM capacity outsourcing","email_template":"A","linkedin_url":"","description":"BIM delivery on tunnels and transport infra"},

# Skanska USA — 10,000+ employees
{"first_name":"Richard","last_name":"Kennedy","email":"richard.kennedy@skanska.com","company":"Skanska USA","title":"CEO","website":"usa.skanska.com","city":"New York, NY","country":"USA","industry":"General Contractor","status":"New","priority_score":92,"services_needed":"BIM Coordination, Clash Detection, 4D","outsourcing_likelihood":"High","pitch_angle":"BIM outsourcing for large GC","email_template":"A","linkedin_url":"","description":"Large GC with peak BIM capacity issues"},
{"first_name":"Mike","last_name":"Woelfel","email":"m.woelfel@skanska.com","company":"Skanska USA","title":"VDC Director","website":"usa.skanska.com","city":"New York, NY","country":"USA","industry":"General Contractor","status":"New","priority_score":90,"services_needed":"Revit, BIM 360, Clash Detection","outsourcing_likelihood":"High","pitch_angle":"BIM coordination during construction phase","email_template":"A","linkedin_url":"","description":"VDC coordination across Skanska US projects"},
{"first_name":"Amy","last_name":"Randolph","email":"a.randolph@skanska.com","company":"Skanska USA","title":"BIM Manager","website":"usa.skanska.com","city":"Chicago, IL","country":"USA","industry":"General Contractor","status":"New","priority_score":85,"services_needed":"MEP Coordination, LOD 400, Clash Detection","outsourcing_likelihood":"High","pitch_angle":"BIM outsourcing during project peaks","email_template":"A","linkedin_url":"","description":"BIM standards and coordination across projects"},

# WSP Global — Canada, 10,000+ employees
{"first_name":"Alexandre","last_name":"L'Heureux","email":"a.lheureux@wsp.com","company":"WSP Global","title":"CEO","website":"wsp.com","city":"Montreal, QC","country":"Canada","industry":"Engineering / Consulting","status":"New","priority_score":92,"services_needed":"BIM Modelling, Scan-to-BIM, Digital Twin","outsourcing_likelihood":"High","pitch_angle":"BIM outsourcing for global engineering firm","email_template":"A","linkedin_url":"","description":"Global engineering firm with peak BIM demand"},
{"first_name":"Nathalie","last_name":"Dupuis","email":"n.dupuis@wsp.com","company":"WSP Global","title":"Director of BIM","website":"wsp.com","city":"Toronto, ON","country":"Canada","industry":"Engineering / Consulting","status":"New","priority_score":90,"services_needed":"BIM Coordination, Revit, 4D Scheduling","outsourcing_likelihood":"High","pitch_angle":"BIM capacity overflow for Canadian projects","email_template":"A","linkedin_url":"","description":"BIM strategy and delivery for Canada region"},
{"first_name":"Chris","last_name":"Bergeron","email":"c.bergeron@wsp.com","company":"WSP Global","title":"BIM Coordinator","website":"wsp.com","city":"Vancouver, BC","country":"Canada","industry":"Engineering / Consulting","status":"New","priority_score":82,"services_needed":"Revit MEP, Clash Detection, BIM 360","outsourcing_likelihood":"High","pitch_angle":"BIM coordination support","email_template":"A","linkedin_url":"","description":"BIM coordination on western Canada projects"},

# Laing O'Rourke — UK, 10,000+ employees
{"first_name":"Ray","last_name":"O'Rourke","email":"info@laingorourke.com","company":"Laing O'Rourke","title":"Chairman","website":"laingorourke.com","city":"London","country":"UK","industry":"General Contractor","status":"New","priority_score":92,"services_needed":"BIM Coordination, LOD 500, 4D Scheduling","outsourcing_likelihood":"High","pitch_angle":"BIM outsourcing for large UK GC","email_template":"A","linkedin_url":"","description":"Major UK GC with complex BIM requirements"},
{"first_name":"James","last_name":"Pellatt","email":"j.pellatt@laingorourke.com","company":"Laing O'Rourke","title":"Digital Engineering Director","website":"laingorourke.com","city":"London","country":"UK","industry":"General Contractor","status":"New","priority_score":90,"services_needed":"BIM, Digital Engineering, Clash Detection","outsourcing_likelihood":"High","pitch_angle":"Digital BIM outsourcing","email_template":"A","linkedin_url":"","description":"Digital engineering strategy across projects"},
{"first_name":"Sarah","last_name":"Marshall","email":"s.marshall@laingorourke.com","company":"Laing O'Rourke","title":"BIM Manager","website":"laingorourke.com","city":"London","country":"UK","industry":"General Contractor","status":"New","priority_score":85,"services_needed":"Revit, NBS, BIM Coordination","outsourcing_likelihood":"High","pitch_angle":"BIM capacity overflow","email_template":"A","linkedin_url":"","description":"BIM coordination and delivery on UK projects"},

# Arup — UK, 10,000+ employees
{"first_name":"Gregory","last_name":"Hodkinson","email":"info@arup.com","company":"Arup","title":"Chairman","website":"arup.com","city":"London","country":"UK","industry":"Engineering / Consulting","status":"New","priority_score":92,"services_needed":"BIM Coordination, Scan-to-BIM, Digital Twin","outsourcing_likelihood":"High","pitch_angle":"BIM outsourcing for global engineering firm","email_template":"A","linkedin_url":"","description":"World-leading engineering consultancy"},
{"first_name":"Dervilla","last_name":"Mitchell","email":"d.mitchell@arup.com","company":"Arup","title":"Digital Practice Lead","website":"arup.com","city":"London","country":"UK","industry":"Engineering / Consulting","status":"New","priority_score":90,"services_needed":"BIM, Digital Twin, Scan-to-BIM","outsourcing_likelihood":"High","pitch_angle":"BIM capacity and digital twin outsourcing","email_template":"A","linkedin_url":"","description":"Leads digital and BIM practice at Arup"},
{"first_name":"Tom","last_name":"Sheridan","email":"t.sheridan@arup.com","company":"Arup","title":"BIM Lead","website":"arup.com","city":"Dublin","country":"UK","industry":"Engineering / Consulting","status":"New","priority_score":85,"services_needed":"Revit, BIM Coordination, MEP","outsourcing_likelihood":"High","pitch_angle":"BIM outsourcing support","email_template":"A","linkedin_url":"","description":"BIM delivery on infrastructure projects"},

# Mott MacDonald — UK, 10,000+ employees
{"first_name":"James","last_name":"Harris","email":"info@mottmac.com","company":"Mott MacDonald","title":"Group CEO","website":"mottmac.com","city":"Croydon","country":"UK","industry":"Engineering / Consulting","status":"New","priority_score":90,"services_needed":"BIM, Scan-to-BIM, 4D Scheduling","outsourcing_likelihood":"High","pitch_angle":"BIM outsourcing for global consulting firm","email_template":"A","linkedin_url":"","description":"Global engineering and management consultancy"},
{"first_name":"Kevin","last_name":"Harrington","email":"k.harrington@mottmac.com","company":"Mott MacDonald","title":"Digital Engineering Director","website":"mottmac.com","city":"Croydon","country":"UK","industry":"Engineering / Consulting","status":"New","priority_score":88,"services_needed":"BIM Coordination, Digital Delivery, Revit","outsourcing_likelihood":"High","pitch_angle":"BIM capacity support","email_template":"A","linkedin_url":"","description":"Digital engineering and BIM lead"},
{"first_name":"Helen","last_name":"Clarke","email":"h.clarke@mottmac.com","company":"Mott MacDonald","title":"BIM Manager","website":"mottmac.com","city":"London","country":"UK","industry":"Engineering / Consulting","status":"New","priority_score":82,"services_needed":"Revit, Clash Detection, BIM 360","outsourcing_likelihood":"High","pitch_angle":"BIM coordination outsourcing","email_template":"A","linkedin_url":"","description":"BIM coordination on transport and water projects"},

# Hochtief — Germany, 10,000+ employees
{"first_name":"Juan","last_name":"Larrainzar","email":"info@hochtief.de","company":"Hochtief","title":"CEO","website":"hochtief.de","city":"Essen","country":"Germany","industry":"General Contractor","status":"New","priority_score":90,"services_needed":"BIM Coordination, LOD 400, Scan-to-BIM","outsourcing_likelihood":"High","pitch_angle":"BIM outsourcing for large German GC","email_template":"A","linkedin_url":"","description":"Major German GC with global project BIM needs"},
{"first_name":"Martin","last_name":"Schmitt","email":"m.schmitt@hochtief.de","company":"Hochtief","title":"BIM Director","website":"hochtief.de","city":"Essen","country":"Germany","industry":"General Contractor","status":"New","priority_score":88,"services_needed":"BIM Coordination, Revit, 4D Scheduling","outsourcing_likelihood":"High","pitch_angle":"BIM capacity overflow","email_template":"A","linkedin_url":"","description":"BIM strategy and delivery for Hochtief Germany"},
{"first_name":"Klaus","last_name":"Wagner","email":"k.wagner@hochtief.de","company":"Hochtief","title":"VDC Manager","website":"hochtief.de","city":"Munich","country":"Germany","industry":"General Contractor","status":"New","priority_score":82,"services_needed":"Revit MEP, Clash Detection, BIM Coordination","outsourcing_likelihood":"High","pitch_angle":"BIM outsourcing during project peaks","email_template":"A","linkedin_url":"","description":"VDC coordination on German infrastructure projects"},

# Strabag — Austria/Germany, 10,000+ employees
{"first_name":"Thomas","last_name":"Birtel","email":"info@strabag.com","company":"Strabag","title":"CEO","website":"strabag.com","city":"Vienna","country":"Germany","industry":"General Contractor","status":"New","priority_score":88,"services_needed":"BIM Modelling, 4D Scheduling, Scan-to-BIM","outsourcing_likelihood":"High","pitch_angle":"BIM outsourcing for pan-European GC","email_template":"A","linkedin_url":"","description":"Major European GC needing BIM offshore support"},
{"first_name":"Hans","last_name":"Kirchner","email":"h.kirchner@strabag.com","company":"Strabag","title":"Digital Construction Director","website":"strabag.com","city":"Vienna","country":"Germany","industry":"General Contractor","status":"New","priority_score":85,"services_needed":"BIM Coordination, Revit, Digital Twin","outsourcing_likelihood":"High","pitch_angle":"BIM capacity during peak construction","email_template":"A","linkedin_url":"","description":"Digital construction strategy at Strabag"},

# Lendlease — Australia, 10,000+ employees
{"first_name":"Tony","last_name":"Lombardo","email":"info@lendlease.com","company":"Lendlease","title":"CEO","website":"lendlease.com","city":"Sydney, NSW","country":"Australia","industry":"General Contractor / Developer","status":"New","priority_score":92,"services_needed":"BIM Coordination, Scan-to-BIM, LOD 400","outsourcing_likelihood":"High","pitch_angle":"BIM outsourcing for Australian developer/GC","email_template":"A","linkedin_url":"","description":"Major Australian GC with complex BIM needs"},
{"first_name":"Dale","last_name":"Connor","email":"d.connor@lendlease.com","company":"Lendlease","title":"Digital Construction Director","website":"lendlease.com","city":"Sydney, NSW","country":"Australia","industry":"General Contractor / Developer","status":"New","priority_score":90,"services_needed":"BIM, 4D Scheduling, Digital Delivery","outsourcing_likelihood":"High","pitch_angle":"BIM outsourcing for large mixed-use projects","email_template":"A","linkedin_url":"","description":"Digital construction strategy and BIM delivery"},
{"first_name":"Karen","last_name":"Ho","email":"k.ho@lendlease.com","company":"Lendlease","title":"BIM Manager","website":"lendlease.com","city":"Melbourne, VIC","country":"Australia","industry":"General Contractor / Developer","status":"New","priority_score":85,"services_needed":"Revit, BIM 360, Clash Detection","outsourcing_likelihood":"High","pitch_angle":"BIM support during design-to-construction","email_template":"A","linkedin_url":"","description":"BIM coordination on major Australian projects"},

# ═══════════════════════════════════════════════════════════════════
# TEMPLATE B — Architecture Firms
# ═══════════════════════════════════════════════════════════════════

# Gensler — USA, 6,000+ employees
{"first_name":"Andy","last_name":"Cohen","email":"info@gensler.com","company":"Gensler","title":"Co-CEO","website":"gensler.com","city":"San Francisco, CA","country":"USA","industry":"Architecture","status":"New","priority_score":92,"services_needed":"Revit CD Documentation, BIM Coordination, Scan-to-BIM","outsourcing_likelihood":"High","pitch_angle":"Revit CD outsourcing during design peaks","email_template":"B","linkedin_url":"","description":"Worlds largest architecture firm — BIM overflow"},
{"first_name":"Diane","last_name":"Hoskins","email":"d.hoskins@gensler.com","company":"Gensler","title":"Co-CEO","website":"gensler.com","city":"Washington, DC","country":"USA","industry":"Architecture","status":"New","priority_score":90,"services_needed":"Revit Modelling, BIM Coordination, Families","outsourcing_likelihood":"High","pitch_angle":"Revit outsourcing for CD phases","email_template":"B","linkedin_url":"","description":"Co-CEO overseeing design delivery globally"},
{"first_name":"Chris","last_name":"Farmer","email":"c.farmer@gensler.com","company":"Gensler","title":"BIM Director","website":"gensler.com","city":"New York, NY","country":"USA","industry":"Architecture","status":"New","priority_score":92,"services_needed":"Revit Families, BIM Standards, CD Documentation","outsourcing_likelihood":"High","pitch_angle":"Revit family creation and CD outsourcing","email_template":"B","linkedin_url":"","description":"BIM standards across all Gensler studios"},
{"first_name":"Tom","last_name":"Ito","email":"t.ito@gensler.com","company":"Gensler","title":"Technology Director","website":"gensler.com","city":"Los Angeles, CA","country":"USA","industry":"Architecture","status":"New","priority_score":88,"services_needed":"Revit, Dynamo, BIM Automation","outsourcing_likelihood":"High","pitch_angle":"BIM automation and workflow scripts","email_template":"B","linkedin_url":"","description":"Technology and BIM automation across studios"},

# HOK — USA, 1,800+ employees
{"first_name":"Bill","last_name":"Hellmuth","email":"info@hok.com","company":"HOK","title":"President","website":"hok.com","city":"Washington, DC","country":"USA","industry":"Architecture","status":"New","priority_score":88,"services_needed":"Revit Documentation, BIM Coordination, Scan-to-BIM","outsourcing_likelihood":"High","pitch_angle":"Revit CD outsourcing for major projects","email_template":"B","linkedin_url":"","description":"Leading US architecture firm — CD crunch phases"},
{"first_name":"Adam","last_name":"Trott","email":"a.trott@hok.com","company":"HOK","title":"Director of BIM","website":"hok.com","city":"New York, NY","country":"USA","industry":"Architecture","status":"New","priority_score":88,"services_needed":"Revit Families, BIM Standards, CD Documentation","outsourcing_likelihood":"High","pitch_angle":"Revit outsourcing during DD/CD phases","email_template":"B","linkedin_url":"","description":"BIM lead across HOK project studios"},
{"first_name":"Laura","last_name":"Ettelman","email":"l.ettelman@hok.com","company":"HOK","title":"Project Architect","website":"hok.com","city":"St. Louis, MO","country":"USA","industry":"Architecture","status":"New","priority_score":80,"services_needed":"Revit Documentation, Sections, Elevations","outsourcing_likelihood":"High","pitch_angle":"CD documentation outsourcing","email_template":"B","linkedin_url":"","description":"Project architect managing CD deliverables"},

# Perkins+Will — USA, 2,500+ employees
{"first_name":"Phil","last_name":"Harrison","email":"info@perkinswill.com","company":"Perkins+Will","title":"CEO","website":"perkinswill.com","city":"Atlanta, GA","country":"USA","industry":"Architecture","status":"New","priority_score":88,"services_needed":"Revit Modelling, BIM Coordination, Scan-to-BIM","outsourcing_likelihood":"High","pitch_angle":"Revit CD outsourcing for large architecture firm","email_template":"B","linkedin_url":"","description":"Major US architecture firm with peak Revit demand"},
{"first_name":"Janice","last_name":"Barnes","email":"j.barnes@perkinswill.com","company":"Perkins+Will","title":"Global Director of Research","website":"perkinswill.com","city":"Chicago, IL","country":"USA","industry":"Architecture","status":"New","priority_score":82,"services_needed":"BIM Research, Revit Families, LOD Documentation","outsourcing_likelihood":"Medium","pitch_angle":"Revit family creation and documentation","email_template":"B","linkedin_url":"","description":"Research and BIM standards"},
{"first_name":"Kevin","last_name":"Pendergast","email":"k.pendergast@perkinswill.com","company":"Perkins+Will","title":"BIM Manager","website":"perkinswill.com","city":"New York, NY","country":"USA","industry":"Architecture","status":"New","priority_score":85,"services_needed":"Revit, BIM Standards, CD Documentation","outsourcing_likelihood":"High","pitch_angle":"CD documentation overflow","email_template":"B","linkedin_url":"","description":"BIM manager for New York studio"},

# Foster + Partners — UK, 1,500+ employees
{"first_name":"Norman","last_name":"Foster","email":"info@fosterandpartners.com","company":"Foster + Partners","title":"Founder","website":"fosterandpartners.com","city":"London","country":"UK","industry":"Architecture","status":"New","priority_score":90,"services_needed":"Revit Modelling, BIM Coordination, Scan-to-BIM","outsourcing_likelihood":"High","pitch_angle":"Revit CD outsourcing for iconic architecture","email_template":"B","linkedin_url":"","description":"World-renowned architecture firm — BIM overflow"},
{"first_name":"David","last_name":"Nelson","email":"d.nelson@fosterandpartners.com","company":"Foster + Partners","title":"Senior Partner","website":"fosterandpartners.com","city":"London","country":"UK","industry":"Architecture","status":"New","priority_score":88,"services_needed":"Revit, BIM Coordination, LOD 500","outsourcing_likelihood":"High","pitch_angle":"BIM support on large architecture commissions","email_template":"B","linkedin_url":"","description":"Senior partner managing major project delivery"},
{"first_name":"Tom","last_name":"Coward","email":"t.coward@fosterandpartners.com","company":"Foster + Partners","title":"BIM Lead","website":"fosterandpartners.com","city":"London","country":"UK","industry":"Architecture","status":"New","priority_score":85,"services_needed":"Revit, Grasshopper, BIM Coordination","outsourcing_likelihood":"High","pitch_angle":"Parametric Revit and BIM coordination","email_template":"B","linkedin_url":"","description":"BIM standards and delivery on major projects"},

# Zaha Hadid Architects — UK, 500+ employees
{"first_name":"Patrik","last_name":"Schumacher","email":"info@zaha-hadid.com","company":"Zaha Hadid Architects","title":"Principal","website":"zaha-hadid.com","city":"London","country":"UK","industry":"Architecture","status":"New","priority_score":88,"services_needed":"Revit, Parametric Modelling, BIM Coordination","outsourcing_likelihood":"High","pitch_angle":"Revit BIM outsourcing for complex geometry","email_template":"B","linkedin_url":"","description":"Iconic architecture firm with complex BIM needs"},
{"first_name":"Jim","last_name":"Heverin","email":"j.heverin@zaha-hadid.com","company":"Zaha Hadid Architects","title":"Director","website":"zaha-hadid.com","city":"London","country":"UK","industry":"Architecture","status":"New","priority_score":85,"services_needed":"Revit Modelling, BIM Coordination","outsourcing_likelihood":"High","pitch_angle":"Complex geometry Revit outsourcing","email_template":"B","linkedin_url":"","description":"Project director on major ZHA commissions"},

# BIG — Bjarke Ingels Group — Denmark, 600+ employees
{"first_name":"Bjarke","last_name":"Ingels","email":"info@big.dk","company":"BIG — Bjarke Ingels Group","title":"Founder","website":"big.dk","city":"Copenhagen","country":"Germany","industry":"Architecture","status":"New","priority_score":88,"services_needed":"Revit Modelling, BIM Coordination, Scan-to-BIM","outsourcing_likelihood":"High","pitch_angle":"Revit outsourcing for high-profile global projects","email_template":"B","linkedin_url":"","description":"World-leading architecture studio with BIM overflow"},
{"first_name":"Andreas","last_name":"Klok Pedersen","email":"a.pedersen@big.dk","company":"BIG — Bjarke Ingels Group","title":"Partner","website":"big.dk","city":"Copenhagen","country":"Germany","industry":"Architecture","status":"New","priority_score":85,"services_needed":"Revit, Grasshopper, BIM Coordination","outsourcing_likelihood":"High","pitch_angle":"BIM and parametric modelling outsourcing","email_template":"B","linkedin_url":"","description":"Partner managing European projects"},

# Woods Bagot — Australia, 700+ employees
{"first_name":"Craig","last_name":"Allardice","email":"info@woodsbagot.com","company":"Woods Bagot","title":"Global CEO","website":"woodsbagot.com","city":"Melbourne, VIC","country":"Australia","industry":"Architecture","status":"New","priority_score":85,"services_needed":"Revit CD Documentation, BIM Coordination","outsourcing_likelihood":"High","pitch_angle":"Revit outsourcing for Australian architecture firm","email_template":"B","linkedin_url":"","description":"Leading Australian architecture firm — CD overflow"},
{"first_name":"Daniel","last_name":"Goldberg","email":"d.goldberg@woodsbagot.com","company":"Woods Bagot","title":"BIM Manager","website":"woodsbagot.com","city":"Sydney, NSW","country":"Australia","industry":"Architecture","status":"New","priority_score":82,"services_needed":"Revit Modelling, Families, CD Documentation","outsourcing_likelihood":"High","pitch_angle":"CD documentation outsourcing","email_template":"B","linkedin_url":"","description":"BIM manager for Sydney and Melbourne studios"},

# ═══════════════════════════════════════════════════════════════════
# TEMPLATE C — Drone / Scan-to-BIM (International)
# ═══════════════════════════════════════════════════════════════════

# Arch Aerial — USA
{"first_name":"David","last_name":"Henley","email":"info@archaerial.com","company":"Arch Aerial","title":"CEO","website":"archaerial.com","city":"Houston, TX","country":"USA","industry":"Drone Survey / Energy / Infrastructure","status":"New","priority_score":85,"services_needed":"Scan-to-BIM, LiDAR Processing, Point Cloud to Revit","outsourcing_likelihood":"High","pitch_angle":"Drone data to BIM conversion","email_template":"C","linkedin_url":"","description":"Energy and infrastructure drone survey — needs BIM output"},
{"first_name":"Scott","last_name":"Howe","email":"s.howe@archaerial.com","company":"Arch Aerial","title":"Operations Director","website":"archaerial.com","city":"Houston, TX","country":"USA","industry":"Drone Survey / Energy / Infrastructure","status":"New","priority_score":82,"services_needed":"Scan-to-BIM, LiDAR Point Cloud","outsourcing_likelihood":"High","pitch_angle":"LiDAR to BIM workflow","email_template":"C","linkedin_url":"","description":"Operations lead — manages survey to deliverable pipeline"},

# Darling Geomatics — USA
{"first_name":"Ryan","last_name":"Nilsson","email":"r.nilsson@darlingltd.com","company":"Darling Geomatics","title":"Director","website":"darlingltd.com","city":"Denver, CO","country":"USA","industry":"Drone Survey / BIM / LiDAR","status":"New","priority_score":90,"services_needed":"Scan-to-BIM, LiDAR Modelling, BIM Coordination","outsourcing_likelihood":"High","pitch_angle":"Scan-to-BIM workflow partner","email_template":"C","linkedin_url":"","description":"LiDAR and drone survey — BIM conversion bottleneck"},
{"first_name":"Maria","last_name":"Castillo","email":"m.castillo@darlingltd.com","company":"Darling Geomatics","title":"Survey Manager","website":"darlingltd.com","city":"Denver, CO","country":"USA","industry":"Drone Survey / BIM / LiDAR","status":"New","priority_score":85,"services_needed":"Scan-to-BIM, Point Cloud Registration","outsourcing_likelihood":"High","pitch_angle":"Point cloud to Revit pipeline","email_template":"C","linkedin_url":"","description":"Survey manager needing BIM output for clients"},
{"first_name":"Jake","last_name":"Morrison","email":"j.morrison@darlingltd.com","company":"Darling Geomatics","title":"BIM Technician","website":"darlingltd.com","city":"Denver, CO","country":"USA","industry":"Drone Survey / BIM / LiDAR","status":"New","priority_score":78,"services_needed":"Revit Modelling from Point Cloud","outsourcing_likelihood":"High","pitch_angle":"Revit modelling from LiDAR data","email_template":"C","linkedin_url":"","description":"BIM technician converting scan data to Revit"},

# ProDroneWorx — UK
{"first_name":"Ian","last_name":"Tansey","email":"info@prodroneworx.co.uk","company":"ProDroneWorx","title":"Managing Director","website":"prodroneworx.co.uk","city":"Beaconsfield","country":"UK","industry":"Drone Survey / BIM / Inspection","status":"New","priority_score":88,"services_needed":"Scan-to-BIM, LiDAR Modelling, BIM Coordination","outsourcing_likelihood":"High","pitch_angle":"Scan-to-BIM workflow partner","email_template":"C","linkedin_url":"linkedin.com/in/ian-tansey-a0593513","description":"Leading UK drone BIM firm — capacity constrained"},
{"first_name":"Phil","last_name":"Carter","email":"p.carter@prodroneworx.co.uk","company":"ProDroneWorx","title":"BIM Lead","website":"prodroneworx.co.uk","city":"Beaconsfield","country":"UK","industry":"Drone Survey / BIM / Inspection","status":"New","priority_score":85,"services_needed":"Revit from Point Cloud, LOD 300-400","outsourcing_likelihood":"High","pitch_angle":"Revit modelling outsourcing","email_template":"C","linkedin_url":"","description":"BIM lead needing overflow capacity"},

# Cyberhawk — UK
{"first_name":"Chris","last_name":"Fleming","email":"info@thecyberhawk.com","company":"Cyberhawk","title":"CEO","website":"thecyberhawk.com","city":"Livingston","country":"UK","industry":"Drone Inspection / Industrial / Oil & Gas","status":"New","priority_score":85,"services_needed":"Scan-to-BIM from inspection data, As-built BIM","outsourcing_likelihood":"High","pitch_angle":"Inspection data to BIM conversion","email_template":"C","linkedin_url":"linkedin.com/company/cyberhawk","description":"Industrial inspection drone — clients need asset BIM"},
{"first_name":"Jonathan","last_name":"Lee","email":"j.lee@thecyberhawk.com","company":"Cyberhawk","title":"Technical Director","website":"thecyberhawk.com","city":"Livingston","country":"UK","industry":"Drone Inspection / Industrial / Oil & Gas","status":"New","priority_score":82,"services_needed":"BIM from drone inspection, LOD 300","outsourcing_likelihood":"High","pitch_angle":"As-built BIM from inspection data","email_template":"C","linkedin_url":"","description":"Technical lead managing inspection data pipeline"},
{"first_name":"David","last_name":"Cowling","email":"d.cowling@thecyberhawk.com","company":"Cyberhawk","title":"Operations Manager","website":"thecyberhawk.com","city":"Aberdeen","country":"UK","industry":"Drone Inspection / Industrial / Oil & Gas","status":"New","priority_score":78,"services_needed":"Point Cloud to BIM, Asset Modelling","outsourcing_likelihood":"High","pitch_angle":"BIM conversion from drone inspection data","email_template":"C","linkedin_url":"","description":"Operations on oil & gas inspection projects"},

# UAVISUALS — Australia
{"first_name":"Aaron","last_name":"Iles","email":"info@uavisuals.com","company":"UAVISUALS","title":"Founder","website":"uavisuals.com","city":"Melbourne, VIC","country":"Australia","industry":"Drone Services / LiDAR / 3D Modelling","status":"New","priority_score":80,"services_needed":"Scan-to-BIM, LiDAR Modelling, 3D Documentation","outsourcing_likelihood":"High","pitch_angle":"Scan-to-BIM workflow partner","email_template":"C","linkedin_url":"","description":"No in-house BIM team to convert drone data"},
{"first_name":"Mark","last_name":"Sullivan","email":"m.sullivan@uavisuals.com","company":"UAVISUALS","title":"Survey Manager","website":"uavisuals.com","city":"Melbourne, VIC","country":"Australia","industry":"Drone Services / LiDAR","status":"New","priority_score":75,"services_needed":"Point Cloud to Revit, LOD 300","outsourcing_likelihood":"High","pitch_angle":"Revit modelling from drone LiDAR","email_template":"C","linkedin_url":"","description":"Survey manager needing BIM output pipeline"},

# RemSense — Australia
{"first_name":"Warren","last_name":"Priestly","email":"info@remsense.com.au","company":"RemSense","title":"CEO","website":"remsense.com.au","city":"Perth, WA","country":"Australia","industry":"Drone / Digital Twin / Asset Management","status":"New","priority_score":82,"services_needed":"Scan-to-BIM, Digital Twin BIM, LOD 400","outsourcing_likelihood":"High","pitch_angle":"Digital twin BIM from drone data","email_template":"C","linkedin_url":"","description":"Digital twin projects need BIM deliverables"},
{"first_name":"Jason","last_name":"Briggs","email":"j.briggs@remsense.com.au","company":"RemSense","title":"Digital Twin Manager","website":"remsense.com.au","city":"Perth, WA","country":"Australia","industry":"Drone / Digital Twin / Asset Management","status":"New","priority_score":80,"services_needed":"Revit from LiDAR, As-built Documentation","outsourcing_likelihood":"High","pitch_angle":"BIM for digital twin projects","email_template":"C","linkedin_url":"","description":"Digital twin delivery — needs BIM modelling partner"},

# Dutch Drone Company — Netherlands
{"first_name":"Thomas","last_name":"de Bruin","email":"info@ddc.works","company":"Dutch Drone Company","title":"CEO","website":"ddc.works","city":"Amsterdam","country":"Netherlands","industry":"Drone Survey / UAV / Cross-Border","status":"New","priority_score":80,"services_needed":"Scan-to-BIM, LiDAR Point Cloud, Revit","outsourcing_likelihood":"High","pitch_angle":"Scan-to-BIM workflow partner","email_template":"C","linkedin_url":"","description":"European drone survey needs BIM conversion partner"},
{"first_name":"Lotte","last_name":"Verhagen","email":"l.verhagen@ddc.works","company":"Dutch Drone Company","title":"Project Manager","website":"ddc.works","city":"Amsterdam","country":"Netherlands","industry":"Drone Survey / UAV","status":"New","priority_score":75,"services_needed":"Point Cloud to BIM, LOD 300","outsourcing_likelihood":"High","pitch_angle":"BIM from drone data","email_template":"C","linkedin_url":"","description":"Project manager for drone survey projects"},

# Altametris — France
{"first_name":"Mathieu","last_name":"Moreau","email":"contact@altametris.com","company":"Altametris","title":"CEO","website":"altametris.com","city":"Paris","country":"France","industry":"Drone Survey / Rail / Infrastructure","status":"New","priority_score":82,"services_needed":"Scan-to-BIM, LiDAR Modelling, Rail BIM","outsourcing_likelihood":"High","pitch_angle":"Rail and infra drone data to BIM","email_template":"C","linkedin_url":"","description":"Rail and infra drone survey — BIM conversion needed"},
{"first_name":"Claire","last_name":"Dupont","email":"c.dupont@altametris.com","company":"Altametris","title":"BIM Manager","website":"altametris.com","city":"Paris","country":"France","industry":"Drone Survey / Rail / Infrastructure","status":"New","priority_score":78,"services_needed":"Revit from Point Cloud, Rail BIM Standards","outsourcing_likelihood":"High","pitch_angle":"Rail BIM from drone data","email_template":"C","linkedin_url":"","description":"BIM manager converting drone data for rail clients"},

# Aerodronics — UAE
{"first_name":"Rabih","last_name":"Bou Rashid","email":"info@aerodronics.ae","company":"Aerodronics","title":"CEO","website":"aerodronics.ae","city":"Dubai","country":"UAE","industry":"Drone Survey / Inspection / Smart City","status":"New","priority_score":82,"services_needed":"Scan-to-BIM, LiDAR, Smart City BIM","outsourcing_likelihood":"High","pitch_angle":"Smart city drone data to BIM","email_template":"C","linkedin_url":"","description":"UAE smart city and construction drone — needs BIM"},
{"first_name":"Ahmed","last_name":"Al Maktoum","email":"a.almaktoum@aerodronics.ae","company":"Aerodronics","title":"Technical Director","website":"aerodronics.ae","city":"Dubai","country":"UAE","industry":"Drone Survey / Inspection","status":"New","priority_score":80,"services_needed":"Point Cloud to Revit, As-built BIM","outsourcing_likelihood":"High","pitch_angle":"As-built BIM from drone survey data","email_template":"C","linkedin_url":"","description":"Technical lead on UAE infrastructure drone projects"},

# Falcon Eye Drones — UAE
{"first_name":"Hany","last_name":"Fares","email":"info@falcon-eye.ae","company":"Falcon Eye Drones","title":"CEO","website":"falcon-eye.ae","city":"Abu Dhabi","country":"UAE","industry":"Drone Survey / Infrastructure / Oil & Gas","status":"New","priority_score":80,"services_needed":"Scan-to-BIM, Progress Monitoring, LiDAR","outsourcing_likelihood":"High","pitch_angle":"Drone data to BIM for Abu Dhabi projects","email_template":"C","linkedin_url":"","description":"Abu Dhabi infra projects need BIM from drone surveys"},
{"first_name":"Khalid","last_name":"Al Ameri","email":"k.alameri@falcon-eye.ae","company":"Falcon Eye Drones","title":"Survey Manager","website":"falcon-eye.ae","city":"Abu Dhabi","country":"UAE","industry":"Drone Survey / Infrastructure","status":"New","priority_score":75,"services_needed":"LiDAR to BIM, LOD 300","outsourcing_likelihood":"High","pitch_angle":"Scan-to-BIM workflow","email_template":"C","linkedin_url":"","description":"Survey manager needing BIM conversion partner"},

# ═══════════════════════════════════════════════════════════════════
# TEMPLATE D — INFRA X (India — Drone / Geospatial / Infrastructure)
# ═══════════════════════════════════════════════════════════════════

# GarudaUAV — India
{"first_name":"Brijesh","last_name":"Pandey","email":"info@garudauav.com","company":"GarudaUAV","title":"Founder & CEO","website":"garudauav.com","city":"Noida, UP","country":"India","industry":"Drone Survey / UAV / AI Platform","status":"New","priority_score":90,"services_needed":"INFRA X Site Monitoring, Scan-to-BIM","outsourcing_likelihood":"High","pitch_angle":"INFRA X Drone Progress Monitoring","email_template":"D","linkedin_url":"","description":"Large infra clients need single-dashboard site visibility"},
{"first_name":"Himanshu","last_name":"Singh","email":"h.singh@garudauav.com","company":"GarudaUAV","title":"Operations Executive","website":"garudauav.com","city":"Noida, UP","country":"India","industry":"Drone Survey / UAV / AI Platform","status":"New","priority_score":85,"services_needed":"INFRA X, Resource Allocation Tracking","outsourcing_likelihood":"High","pitch_angle":"INFRA X for infra project monitoring","email_template":"D","linkedin_url":"","description":"Operations lead managing drone survey delivery"},
{"first_name":"Priya","last_name":"Mehta","email":"p.mehta@garudauav.com","company":"GarudaUAV","title":"Business Development Manager","website":"garudauav.com","city":"Noida, UP","country":"India","industry":"Drone Survey / UAV","status":"New","priority_score":80,"services_needed":"INFRA X Partnership, Joint Bid","outsourcing_likelihood":"High","pitch_angle":"INFRA X collaboration opportunity","email_template":"D","linkedin_url":"","description":"BD looking for tech partners for infra projects"},

# IG Drones — India
{"first_name":"Ranjit","last_name":"Singh","email":"info@igdrones.com","company":"IG Drones","title":"CEO","website":"igdrones.com","city":"Gurugram, Haryana","country":"India","industry":"Drone Survey / GIS / Mapping","status":"New","priority_score":85,"services_needed":"INFRA X Site Monitoring, Compare View","outsourcing_likelihood":"High","pitch_angle":"INFRA X Drone Progress Monitoring","email_template":"D","linkedin_url":"","description":"Infrastructure clients want one-desk site visibility"},
{"first_name":"Abhishek","last_name":"Kumar","email":"a.kumar@igdrones.com","company":"IG Drones","title":"Technical Director","website":"igdrones.com","city":"Gurugram, Haryana","country":"India","industry":"Drone Survey / GIS","status":"New","priority_score":82,"services_needed":"INFRA X, Automated Reports, Progress Monitoring","outsourcing_likelihood":"High","pitch_angle":"INFRA X technology partnership","email_template":"D","linkedin_url":"","description":"Technical lead on GIS and drone survey projects"},
{"first_name":"Neha","last_name":"Sharma","email":"n.sharma@igdrones.com","company":"IG Drones","title":"Project Manager","website":"igdrones.com","city":"Gurugram, Haryana","country":"India","industry":"Drone Survey / GIS","status":"New","priority_score":75,"services_needed":"INFRA X Site Reports, Resource Tracking","outsourcing_likelihood":"High","pitch_angle":"Automated progress reports for clients","email_template":"D","linkedin_url":"","description":"PM managing delivery on infrastructure drone projects"},

# Skylark Drones — India
{"first_name":"Ankit","last_name":"Kumar","email":"info@skylarkdrones.com","company":"Skylark Drones","title":"CEO","website":"skylarkdrones.com","city":"Bangalore","country":"India","industry":"Drone Survey / Mining / Infrastructure","status":"New","priority_score":88,"services_needed":"INFRA X, Resource Allocation, Progress Reports","outsourcing_likelihood":"High","pitch_angle":"INFRA X Drone Progress Monitoring","email_template":"D","linkedin_url":"linkedin.com/company/skylark-drones","description":"Mining and infra projects lack real-time resource visibility"},
{"first_name":"Srikanth","last_name":"Reddy","email":"s.reddy@skylarkdrones.com","company":"Skylark Drones","title":"Operations Head","website":"skylarkdrones.com","city":"Bangalore","country":"India","industry":"Drone Survey / Mining / Infrastructure","status":"New","priority_score":85,"services_needed":"INFRA X Site Monitoring, Compare View","outsourcing_likelihood":"High","pitch_angle":"INFRA X site intelligence platform","email_template":"D","linkedin_url":"","description":"Operations head managing multi-site drone deployments"},
{"first_name":"Kavya","last_name":"Nair","email":"k.nair@skylarkdrones.com","company":"Skylark Drones","title":"Business Development","website":"skylarkdrones.com","city":"Bangalore","country":"India","industry":"Drone Survey / Mining","status":"New","priority_score":78,"services_needed":"INFRA X Partnership","outsourcing_likelihood":"High","pitch_angle":"INFRA X collaboration for mining clients","email_template":"D","linkedin_url":"","description":"BD for new mining and infra project opportunities"},

# IdeaForge — India
{"first_name":"Vipul","last_name":"Kher","email":"info@ideaforgedrones.com","company":"IdeaForge","title":"CEO","website":"ideaforgedrones.com","city":"Mumbai","country":"India","industry":"Drone Manufacturer / Services / Defence","status":"New","priority_score":85,"services_needed":"INFRA X Site Monitoring, Progress Reporting","outsourcing_likelihood":"High","pitch_angle":"INFRA X for infrastructure and defence clients","email_template":"D","linkedin_url":"","description":"Large infra and defence clients need ground progress intelligence"},
{"first_name":"Rahul","last_name":"Singh","email":"r.singh@ideaforgedrones.com","company":"IdeaForge","title":"Sales Director","website":"ideaforgedrones.com","city":"Mumbai","country":"India","industry":"Drone Manufacturer / Services","status":"New","priority_score":80,"services_needed":"INFRA X, One-desk Monitoring","outsourcing_likelihood":"High","pitch_angle":"INFRA X as add-on service for clients","email_template":"D","linkedin_url":"","description":"Sales director positioning INFRA X as premium offering"},

# Aarav Unmanned Systems — India
{"first_name":"Rajat","last_name":"Kulshrestha","email":"contact@aarav-unmanned.com","company":"Aarav Unmanned Systems","title":"Co-Founder","website":"aarav-unmanned.com","city":"Pune","country":"India","industry":"Drone Survey / GIS / Agriculture","status":"New","priority_score":80,"services_needed":"INFRA X Site Monitoring","outsourcing_likelihood":"High","pitch_angle":"INFRA X for infrastructure monitoring","email_template":"D","linkedin_url":"","description":"Infrastructure monitoring gaps on large project sites"},
{"first_name":"Nitin","last_name":"Gupta","email":"n.gupta@aarav-unmanned.com","company":"Aarav Unmanned Systems","title":"Technical Lead","website":"aarav-unmanned.com","city":"Pune","country":"India","industry":"Drone Survey / GIS","status":"New","priority_score":75,"services_needed":"INFRA X, Automated Reports","outsourcing_likelihood":"High","pitch_angle":"INFRA X as tech platform for GIS clients","email_template":"D","linkedin_url":"","description":"Technical lead on survey and mapping projects"},

# Garud Survey — India
{"first_name":"Gaurav","last_name":"Srivastava","email":"info@garudsurvey.com","company":"Garud Survey","title":"CEO","website":"garudsurvey.com","city":"Delhi","country":"India","industry":"Drone Survey / Geospatial / Mining","status":"New","priority_score":88,"services_needed":"INFRA X Site Monitoring, Resource Allocation","outsourcing_likelihood":"High","pitch_angle":"INFRA X for mining and infra monitoring","email_template":"D","linkedin_url":"","description":"Mining and infra clients need real-time progress monitoring"},
{"first_name":"Deepak","last_name":"Yadav","email":"d.yadav@garudsurvey.com","company":"Garud Survey","title":"Operations Manager","website":"garudsurvey.com","city":"Delhi","country":"India","industry":"Drone Survey / Geospatial","status":"New","priority_score":80,"services_needed":"INFRA X, Compare View, Deviation Alerts","outsourcing_likelihood":"High","pitch_angle":"Automated site progress reports","email_template":"D","linkedin_url":"","description":"Operations manager for large survey deployments"},

# Equinox Drones — India
{"first_name":"Prashant","last_name":"Chandak","email":"info@equinoxsdrones.com","company":"Equinox Drones","title":"CEO","website":"equinoxsdrones.com","city":"Hyderabad","country":"India","industry":"Drone / UAV Inspection / Aerial Survey","status":"New","priority_score":82,"services_needed":"INFRA X Compare View, Resource Allocation","outsourcing_likelihood":"High","pitch_angle":"INFRA X platform for multi-site monitoring","email_template":"D","linkedin_url":"","description":"No single platform to monitor multiple sites simultaneously"},
{"first_name":"Suresh","last_name":"Babu","email":"s.babu@equinoxsdrones.com","company":"Equinox Drones","title":"Technical Director","website":"equinoxsdrones.com","city":"Hyderabad","country":"India","industry":"Drone / UAV Inspection","status":"New","priority_score":78,"services_needed":"INFRA X, One-desk Monitoring","outsourcing_likelihood":"High","pitch_angle":"INFRA X as premium service layer","email_template":"D","linkedin_url":"","description":"Technical director on drone inspection projects"},
]

imported = 0
skipped  = 0
for lead in leads:
    lead.setdefault("phone", "")
    lead.setdefault("follow_up_stage", "")
    try:
        db.create_lead(lead)
        imported += 1
    except Exception as e:
        skipped += 1

print(f"\n{'='*55}")
print(f"  BIM + Drone Leads Import Complete")
print(f"{'='*55}")
print(f"  Imported : {imported}")
print(f"  Skipped  : {skipped} (likely duplicates)")
print(f"  Total    : {len(leads)}")
print(f"\n  Open: http://localhost:5000/leads")
