import sys
sys.path.insert(0, r"C:\Users\Kishan\BIM_CRM")
import database as db
db.init_db()

leads = [
{"first_name":"Karl","last_name":"Almstead","email":"k.almstead@turnerconstruction.com","company":"Turner Construction","title":"VDC Director","phone":"","website":"turnerconstruction.com","city":"New York","country":"USA","industry":"General Contractor","status":"New","priority_score":95,"services_needed":"VDC, BIM Coordination, Clash Detection","outsourcing_likelihood":"High","pitch_angle":"BIM outsourcing during project peak","email_template":"A","linkedin_url":"","follow_up_stage":"","description":"Manages all VDC operations across USA"},
{"first_name":"Jennifer","last_name":"Rice","email":"j.rice@turnerconstruction.com","company":"Turner Construction","title":"BIM Manager","phone":"","website":"turnerconstruction.com","city":"New York","country":"USA","industry":"General Contractor","status":"New","priority_score":90,"services_needed":"Revit Modelling, Clash Detection","outsourcing_likelihood":"High","pitch_angle":"BIM capacity during peak phases","email_template":"A","linkedin_url":"","follow_up_stage":"","description":"BIM standards and delivery"},
{"first_name":"Troy","last_name":"Rudd","email":"troy.rudd@aecom.com","company":"AECOM","title":"CEO","phone":"","website":"aecom.com","city":"Dallas, TX","country":"USA","industry":"Engineering / Infrastructure","status":"New","priority_score":95,"services_needed":"BIM, Scan-to-BIM, 4D Scheduling","outsourcing_likelihood":"High","pitch_angle":"BIM outsourcing for infrastructure projects","email_template":"A","linkedin_url":"","follow_up_stage":"","description":"Global infrastructure firm, peak BIM demand"},
{"first_name":"Lara","last_name":"Washington","email":"l.washington@aecom.com","company":"AECOM","title":"Digital Delivery Director","phone":"","website":"aecom.com","city":"Los Angeles, CA","country":"USA","industry":"Engineering / Infrastructure","status":"New","priority_score":92,"services_needed":"BIM Coordination, Revit, Digital Twin","outsourcing_likelihood":"High","pitch_angle":"BIM capacity overflow","email_template":"A","linkedin_url":"","follow_up_stage":"","description":"BIM and digital delivery lead"},
{"first_name":"James","last_name":"Simmons","email":"j.simmons@aecom.com","company":"AECOM","title":"BIM Manager","phone":"","website":"aecom.com","city":"New York, NY","country":"USA","industry":"Engineering / Infrastructure","status":"New","priority_score":88,"services_needed":"Revit Modelling, MEP Coordination, Clash Detection","outsourcing_likelihood":"High","pitch_angle":"BIM outsourcing support","email_template":"A","linkedin_url":"","follow_up_stage":"","description":"Day-to-day BIM delivery on projects"},
{"first_name":"Carey","last_name":"Smith","email":"c.smith@parsons.com","company":"Parsons Corporation","title":"CEO","phone":"","website":"parsons.com","city":"Centreville, VA","country":"USA","industry":"Engineering / Defence / Infrastructure","status":"New","priority_score":95,"services_needed":"BIM Modelling, 4D/5D, Dynamo Automation","outsourcing_likelihood":"High","pitch_angle":"BIM outsourcing for mega infrastructure","email_template":"A","linkedin_url":"","follow_up_stage":"","description":"110km Floating Tunnel BIM capacity needed"},
{"first_name":"Steve","last_name":"Demetriou","email":"s.demetriou@jacobs.com","company":"Jacobs Engineering","title":"CEO","phone":"","website":"jacobs.com","city":"Dallas, TX","country":"USA","industry":"Engineering / Consulting","status":"New","priority_score":90,"services_needed":"BIM Modelling, 4D Scheduling, Scan-to-BIM","outsourcing_likelihood":"High","pitch_angle":"BIM capacity for large infrastructure","email_template":"A","linkedin_url":"","follow_up_stage":"","description":"Global engineering firm needing BIM support"},
{"first_name":"Richard","last_name":"Kennedy","email":"r.kennedy@skanska.com","company":"Skanska USA","title":"CEO","phone":"","website":"usa.skanska.com","city":"New York, NY","country":"USA","industry":"General Contractor","status":"New","priority_score":92,"services_needed":"BIM Coordination, Clash Detection, 4D","outsourcing_likelihood":"High","pitch_angle":"BIM outsourcing for large GC","email_template":"A","linkedin_url":"","follow_up_stage":"","description":"Large GC with peak BIM capacity issues"},
{"first_name":"Mike","last_name":"Woelfel","email":"m.woelfel@skanska.com","company":"Skanska USA","title":"VDC Director","phone":"","website":"usa.skanska.com","city":"New York, NY","country":"USA","industry":"General Contractor","status":"New","priority_score":90,"services_needed":"Revit, BIM 360, Clash Detection","outsourcing_likelihood":"High","pitch_angle":"BIM coordination during construction phase","email_template":"A","linkedin_url":"","follow_up_stage":"","description":"VDC coordination across Skanska US projects"},
{"first_name":"Alexandre","last_name":"Lheureux","email":"a.lheureux@wsp.com","company":"WSP Global","title":"CEO","phone":"","website":"wsp.com","city":"Montreal, QC","country":"Canada","industry":"Engineering / Consulting","status":"New","priority_score":92,"services_needed":"BIM Modelling, Scan-to-BIM, Digital Twin","outsourcing_likelihood":"High","pitch_angle":"BIM outsourcing for global engineering firm","email_template":"A","linkedin_url":"","follow_up_stage":"","description":"Global engineering firm with peak BIM demand"},
{"first_name":"Nathalie","last_name":"Dupuis","email":"n.dupuis@wsp.com","company":"WSP Global","title":"Director of BIM","phone":"","website":"wsp.com","city":"Toronto, ON","country":"Canada","industry":"Engineering / Consulting","status":"New","priority_score":90,"services_needed":"BIM Coordination, Revit, 4D Scheduling","outsourcing_likelihood":"High","pitch_angle":"BIM capacity overflow for Canadian projects","email_template":"A","linkedin_url":"","follow_up_stage":"","description":"BIM strategy and delivery for Canada region"},
{"first_name":"Tony","last_name":"Lombardo","email":"info.aus@lendlease.com","company":"Lendlease","title":"CEO","phone":"","website":"lendlease.com","city":"Sydney, NSW","country":"Australia","industry":"General Contractor / Developer","status":"New","priority_score":92,"services_needed":"BIM Coordination, Scan-to-BIM, LOD 400","outsourcing_likelihood":"High","pitch_angle":"BIM outsourcing for Australian developer/GC","email_template":"A","linkedin_url":"","follow_up_stage":"","description":"Major Australian GC with complex BIM needs"},
{"first_name":"Dale","last_name":"Connor","email":"d.connor@lendlease.com","company":"Lendlease","title":"Digital Construction Director","phone":"","website":"lendlease.com","city":"Sydney, NSW","country":"Australia","industry":"General Contractor / Developer","status":"New","priority_score":90,"services_needed":"BIM, 4D Scheduling, Digital Delivery","outsourcing_likelihood":"High","pitch_angle":"BIM outsourcing for large mixed-use projects","email_template":"A","linkedin_url":"","follow_up_stage":"","description":"Digital construction strategy and BIM delivery"},
{"first_name":"Gregory","last_name":"Hodkinson","email":"info@arup.com","company":"Arup","title":"Chairman","phone":"","website":"arup.com","city":"London","country":"UK","industry":"Engineering / Consulting","status":"New","priority_score":92,"services_needed":"BIM Coordination, Scan-to-BIM, Digital Twin","outsourcing_likelihood":"High","pitch_angle":"BIM outsourcing for global engineering firm","email_template":"A","linkedin_url":"","follow_up_stage":"","description":"World-leading engineering consultancy"},
{"first_name":"Dervilla","last_name":"Mitchell","email":"d.mitchell@arup.com","company":"Arup","title":"Digital Practice Lead","phone":"","website":"arup.com","city":"London","country":"UK","industry":"Engineering / Consulting","status":"New","priority_score":90,"services_needed":"BIM, Digital Twin, Scan-to-BIM","outsourcing_likelihood":"High","pitch_angle":"BIM capacity and digital twin outsourcing","email_template":"A","linkedin_url":"","follow_up_stage":"","description":"Leads digital and BIM practice at Arup"},
{"first_name":"Ray","last_name":"ORourke","email":"info@laingorourke.com","company":"Laing ORourke","title":"Chairman","phone":"","website":"laingorourke.com","city":"London","country":"UK","industry":"General Contractor","status":"New","priority_score":92,"services_needed":"BIM Coordination, LOD 500, 4D Scheduling","outsourcing_likelihood":"High","pitch_angle":"BIM outsourcing for large UK GC","email_template":"A","linkedin_url":"","follow_up_stage":"","description":"Major UK GC with complex BIM requirements"},
{"first_name":"James","last_name":"Harris","email":"info@mottmac.com","company":"Mott MacDonald","title":"Group CEO","phone":"","website":"mottmac.com","city":"Croydon","country":"UK","industry":"Engineering / Consulting","status":"New","priority_score":90,"services_needed":"BIM, Scan-to-BIM, 4D Scheduling","outsourcing_likelihood":"High","pitch_angle":"BIM outsourcing for global consulting firm","email_template":"A","linkedin_url":"","follow_up_stage":"","description":"Global engineering and management consultancy"},
{"first_name":"Andy","last_name":"Cohen","email":"info@gensler.com","company":"Gensler","title":"Co-CEO","phone":"","website":"gensler.com","city":"San Francisco, CA","country":"USA","industry":"Architecture","status":"New","priority_score":92,"services_needed":"Revit CD Documentation, BIM Coordination","outsourcing_likelihood":"High","pitch_angle":"Revit CD outsourcing during design peaks","email_template":"B","linkedin_url":"","follow_up_stage":"","description":"Worlds largest architecture firm BIM overflow"},
{"first_name":"Chris","last_name":"Farmer","email":"c.farmer@gensler.com","company":"Gensler","title":"BIM Director","phone":"","website":"gensler.com","city":"New York, NY","country":"USA","industry":"Architecture","status":"New","priority_score":92,"services_needed":"Revit Families, BIM Standards, CD Documentation","outsourcing_likelihood":"High","pitch_angle":"Revit family creation and CD outsourcing","email_template":"B","linkedin_url":"","follow_up_stage":"","description":"BIM standards across all Gensler studios"},
{"first_name":"Tom","last_name":"Ito","email":"t.ito@gensler.com","company":"Gensler","title":"Technology Director","phone":"","website":"gensler.com","city":"Los Angeles, CA","country":"USA","industry":"Architecture","status":"New","priority_score":88,"services_needed":"Revit, Dynamo, BIM Automation","outsourcing_likelihood":"High","pitch_angle":"BIM automation and workflow scripts","email_template":"B","linkedin_url":"","follow_up_stage":"","description":"Technology and BIM automation across studios"},
{"first_name":"Bill","last_name":"Hellmuth","email":"info@hok.com","company":"HOK","title":"President","phone":"","website":"hok.com","city":"Washington, DC","country":"USA","industry":"Architecture","status":"New","priority_score":88,"services_needed":"Revit Documentation, BIM Coordination","outsourcing_likelihood":"High","pitch_angle":"Revit CD outsourcing for major projects","email_template":"B","linkedin_url":"","follow_up_stage":"","description":"Leading US architecture firm CD crunch phases"},
{"first_name":"Phil","last_name":"Harrison","email":"info@perkinswill.com","company":"Perkins+Will","title":"CEO","phone":"","website":"perkinswill.com","city":"Atlanta, GA","country":"USA","industry":"Architecture","status":"New","priority_score":88,"services_needed":"Revit Modelling, BIM Coordination","outsourcing_likelihood":"High","pitch_angle":"Revit CD outsourcing for large architecture firm","email_template":"B","linkedin_url":"","follow_up_stage":"","description":"Major US architecture firm with peak Revit demand"},
{"first_name":"Norman","last_name":"Foster","email":"info@fosterandpartners.com","company":"Foster and Partners","title":"Founder","phone":"","website":"fosterandpartners.com","city":"London","country":"UK","industry":"Architecture","status":"New","priority_score":90,"services_needed":"Revit Modelling, BIM Coordination, Scan-to-BIM","outsourcing_likelihood":"High","pitch_angle":"Revit CD outsourcing for iconic architecture","email_template":"B","linkedin_url":"","follow_up_stage":"","description":"World-renowned architecture firm BIM overflow"},
{"first_name":"Patrik","last_name":"Schumacher","email":"info@zaha-hadid.com","company":"Zaha Hadid Architects","title":"Principal","phone":"","website":"zaha-hadid.com","city":"London","country":"UK","industry":"Architecture","status":"New","priority_score":88,"services_needed":"Revit, Parametric Modelling, BIM Coordination","outsourcing_likelihood":"High","pitch_angle":"Revit BIM outsourcing for complex geometry","email_template":"B","linkedin_url":"","follow_up_stage":"","description":"Iconic architecture firm with complex BIM needs"},
{"first_name":"Bjarke","last_name":"Ingels","email":"info@big.dk","company":"BIG Bjarke Ingels Group","title":"Founder","phone":"","website":"big.dk","city":"Copenhagen","country":"Germany","industry":"Architecture","status":"New","priority_score":88,"services_needed":"Revit Modelling, BIM Coordination","outsourcing_likelihood":"High","pitch_angle":"Revit outsourcing for high-profile global projects","email_template":"B","linkedin_url":"","follow_up_stage":"","description":"World-leading architecture studio with BIM overflow"},
{"first_name":"Craig","last_name":"Allardice","email":"info@woodsbagot.com","company":"Woods Bagot","title":"Global CEO","phone":"","website":"woodsbagot.com","city":"Melbourne, VIC","country":"Australia","industry":"Architecture","status":"New","priority_score":85,"services_needed":"Revit CD Documentation, BIM Coordination","outsourcing_likelihood":"High","pitch_angle":"Revit outsourcing for Australian architecture firm","email_template":"B","linkedin_url":"","follow_up_stage":"","description":"Leading Australian architecture firm CD overflow"},
{"first_name":"David","last_name":"Henley","email":"info@archaerial.com","company":"Arch Aerial","title":"CEO","phone":"","website":"archaerial.com","city":"Houston, TX","country":"USA","industry":"Drone Survey / Infrastructure","status":"New","priority_score":85,"services_needed":"Scan-to-BIM, LiDAR Processing, Point Cloud to Revit","outsourcing_likelihood":"High","pitch_angle":"Drone data to BIM conversion","email_template":"C","linkedin_url":"","follow_up_stage":"","description":"Energy and infrastructure drone survey needs BIM output"},
{"first_name":"Scott","last_name":"Howe","email":"s.howe@archaerial.com","company":"Arch Aerial","title":"Operations Director","phone":"","website":"archaerial.com","city":"Houston, TX","country":"USA","industry":"Drone Survey / Infrastructure","status":"New","priority_score":82,"services_needed":"Scan-to-BIM, LiDAR Point Cloud","outsourcing_likelihood":"High","pitch_angle":"LiDAR to BIM workflow","email_template":"C","linkedin_url":"","follow_up_stage":"","description":"Operations lead manages survey to deliverable pipeline"},
{"first_name":"Ryan","last_name":"Nilsson","email":"r.nilsson@darlingltd.com","company":"Darling Geomatics","title":"Director","phone":"","website":"darlingltd.com","city":"Denver, CO","country":"USA","industry":"Drone Survey / BIM / LiDAR","status":"New","priority_score":90,"services_needed":"Scan-to-BIM, LiDAR Modelling, BIM Coordination","outsourcing_likelihood":"High","pitch_angle":"Scan-to-BIM workflow partner","email_template":"C","linkedin_url":"","follow_up_stage":"","description":"LiDAR and drone survey BIM conversion bottleneck"},
{"first_name":"Maria","last_name":"Castillo","email":"m.castillo@darlingltd.com","company":"Darling Geomatics","title":"Survey Manager","phone":"","website":"darlingltd.com","city":"Denver, CO","country":"USA","industry":"Drone Survey / BIM / LiDAR","status":"New","priority_score":85,"services_needed":"Scan-to-BIM, Point Cloud Registration","outsourcing_likelihood":"High","pitch_angle":"Point cloud to Revit pipeline","email_template":"C","linkedin_url":"","follow_up_stage":"","description":"Survey manager needing BIM output for clients"},
{"first_name":"Ian","last_name":"Tansey","email":"info@prodroneworx.co.uk","company":"ProDroneWorx","title":"Managing Director","phone":"+44 7805 864642","website":"prodroneworx.co.uk","city":"Beaconsfield","country":"UK","industry":"Drone Survey / BIM / Inspection","status":"New","priority_score":88,"services_needed":"Scan-to-BIM, LiDAR Modelling","outsourcing_likelihood":"High","pitch_angle":"Scan-to-BIM workflow partner","email_template":"C","linkedin_url":"linkedin.com/in/ian-tansey-a0593513","follow_up_stage":"","description":"Leading UK drone BIM firm capacity constrained"},
{"first_name":"Chris","last_name":"Fleming","email":"info@thecyberhawk.com","company":"Cyberhawk","title":"CEO","phone":"","website":"thecyberhawk.com","city":"Livingston","country":"UK","industry":"Drone Inspection / Industrial","status":"New","priority_score":85,"services_needed":"Scan-to-BIM from inspection data","outsourcing_likelihood":"High","pitch_angle":"Inspection data to BIM conversion","email_template":"C","linkedin_url":"linkedin.com/company/cyberhawk","follow_up_stage":"","description":"Industrial inspection drone clients need asset BIM"},
{"first_name":"Aaron","last_name":"Iles","email":"info@uavisuals.com","company":"UAVISUALS","title":"Founder","phone":"1300711965","website":"uavisuals.com","city":"Melbourne, VIC","country":"Australia","industry":"Drone Services / LiDAR","status":"New","priority_score":80,"services_needed":"Scan-to-BIM, LiDAR Modelling","outsourcing_likelihood":"High","pitch_angle":"Scan-to-BIM workflow partner","email_template":"C","linkedin_url":"","follow_up_stage":"","description":"No in-house BIM team for scan-to-BIM conversion"},
{"first_name":"Warren","last_name":"Priestly","email":"info@remsense.com.au","company":"RemSense","title":"CEO","phone":"","website":"remsense.com.au","city":"Perth, WA","country":"Australia","industry":"Drone / Digital Twin / UAV","status":"New","priority_score":82,"services_needed":"Scan-to-BIM, Digital Twin BIM","outsourcing_likelihood":"High","pitch_angle":"Digital twin BIM from drone data","email_template":"C","linkedin_url":"","follow_up_stage":"","description":"Digital twin projects need BIM deliverables"},
{"first_name":"Thomas","last_name":"deBruin","email":"info@ddc.works","company":"Dutch Drone Company","title":"CEO","phone":"","website":"ddc.works","city":"Amsterdam","country":"Netherlands","industry":"Drone Survey / UAV","status":"New","priority_score":80,"services_needed":"Scan-to-BIM, LiDAR Point Cloud","outsourcing_likelihood":"High","pitch_angle":"Scan-to-BIM workflow partner","email_template":"C","linkedin_url":"","follow_up_stage":"","description":"European drone survey needs BIM conversion partner"},
{"first_name":"Mathieu","last_name":"Moreau","email":"contact@altametris.com","company":"Altametris","title":"CEO","phone":"","website":"altametris.com","city":"Paris","country":"France","industry":"Drone Survey / Rail / Infrastructure","status":"New","priority_score":82,"services_needed":"Scan-to-BIM, LiDAR Modelling, Rail BIM","outsourcing_likelihood":"High","pitch_angle":"Rail and infra drone data to BIM","email_template":"C","linkedin_url":"","follow_up_stage":"","description":"Rail and infra drone survey BIM conversion needed"},
{"first_name":"Rabih","last_name":"BouRashid","email":"info@aerodronics.ae","company":"Aerodronics","title":"CEO","phone":"","website":"aerodronics.ae","city":"Dubai","country":"UAE","industry":"Drone Survey / Inspection / Smart City","status":"New","priority_score":82,"services_needed":"Scan-to-BIM, LiDAR, Smart City BIM","outsourcing_likelihood":"High","pitch_angle":"Smart city drone data to BIM","email_template":"C","linkedin_url":"","follow_up_stage":"","description":"UAE smart city and construction drone needs BIM"},
{"first_name":"Hany","last_name":"Fares","email":"info@falcon-eye.ae","company":"Falcon Eye Drones","title":"CEO","phone":"","website":"falcon-eye.ae","city":"Abu Dhabi","country":"UAE","industry":"Drone Survey / Infrastructure / Oil and Gas","status":"New","priority_score":80,"services_needed":"Scan-to-BIM, Progress Monitoring, LiDAR","outsourcing_likelihood":"High","pitch_angle":"Drone data to BIM for Abu Dhabi projects","email_template":"C","linkedin_url":"","follow_up_stage":"","description":"Abu Dhabi infra projects need BIM from drone surveys"},
{"first_name":"Brijesh","last_name":"Pandey","email":"brijesh@garudauav.com","company":"GarudaUAV","title":"Founder & CEO","phone":"","website":"garudauav.com","city":"Noida, UP","country":"India","industry":"Drone Survey / UAV / AI","status":"New","priority_score":90,"services_needed":"INFRA X Site Monitoring, Scan-to-BIM","outsourcing_likelihood":"High","pitch_angle":"INFRA X Drone Progress Monitoring","email_template":"D","linkedin_url":"","follow_up_stage":"","description":"Large infra clients need single-dashboard site visibility"},
{"first_name":"Himanshu","last_name":"Singh","email":"himanshu@garudauav.com","company":"GarudaUAV","title":"Operations Executive","phone":"","website":"garudauav.com","city":"Noida, UP","country":"India","industry":"Drone Survey / UAV","status":"New","priority_score":82,"services_needed":"INFRA X, Resource Allocation Tracking","outsourcing_likelihood":"High","pitch_angle":"INFRA X for infra project monitoring","email_template":"D","linkedin_url":"","follow_up_stage":"","description":"Operations lead managing drone survey delivery"},
{"first_name":"Ranjit","last_name":"Singh","email":"info@igdrones.com","company":"IG Drones","title":"CEO","phone":"","website":"igdrones.com","city":"Gurugram, Haryana","country":"India","industry":"Drone Survey / GIS / Mapping","status":"New","priority_score":85,"services_needed":"INFRA X Site Monitoring, Compare View","outsourcing_likelihood":"High","pitch_angle":"INFRA X Drone Progress Monitoring","email_template":"D","linkedin_url":"","follow_up_stage":"","description":"Infrastructure clients want one-desk site visibility"},
{"first_name":"Ankit","last_name":"Kumar","email":"ankit@skylarkdrones.com","company":"Skylark Drones","title":"CEO","phone":"","website":"skylarkdrones.com","city":"Bangalore","country":"India","industry":"Drone Survey / Mining / Infra","status":"New","priority_score":88,"services_needed":"INFRA X, Resource Allocation, Reports","outsourcing_likelihood":"High","pitch_angle":"INFRA X Drone Progress Monitoring","email_template":"D","linkedin_url":"linkedin.com/company/skylark-drones","follow_up_stage":"","description":"Mining and infra projects lack real-time resource visibility"},
{"first_name":"Vipul","last_name":"Kher","email":"vipul@ideaforgedrones.com","company":"IdeaForge","title":"CEO","phone":"","website":"ideaforgedrones.com","city":"Mumbai","country":"India","industry":"Drone Manufacturer / Services","status":"New","priority_score":85,"services_needed":"INFRA X Site Monitoring","outsourcing_likelihood":"High","pitch_angle":"INFRA X Drone Progress Monitoring","email_template":"D","linkedin_url":"","follow_up_stage":"","description":"Large infra clients need ground progress intelligence"},
{"first_name":"Prashant","last_name":"Chandak","email":"prashant@equinoxsdrones.com","company":"Equinox Drones","title":"CEO","phone":"","website":"equinoxsdrones.com","city":"Hyderabad","country":"India","industry":"Drone / UAV Inspection / Aerial","status":"New","priority_score":82,"services_needed":"INFRA X Compare View, Resource Allocation","outsourcing_likelihood":"High","pitch_angle":"INFRA X Drone Progress Monitoring","email_template":"D","linkedin_url":"","follow_up_stage":"","description":"No single platform to monitor multiple sites"},
{"first_name":"Rajat","last_name":"Kulshrestha","email":"rajat@aarav-unmanned.com","company":"Aarav Unmanned Systems","title":"Co-Founder","phone":"","website":"aarav-unmanned.com","city":"Pune","country":"India","industry":"Drone Survey / GIS","status":"New","priority_score":80,"services_needed":"INFRA X Site Monitoring","outsourcing_likelihood":"High","pitch_angle":"INFRA X Drone Progress Monitoring","email_template":"D","linkedin_url":"","follow_up_stage":"","description":"Infrastructure monitoring gaps on large project sites"},
]

imported = 0
skipped  = 0
for lead in leads:
    try:
        db.create_lead(lead)
        imported += 1
    except Exception as e:
        skipped += 1

total = db.get_all_leads()
print(f"Imported: {imported}  |  Skipped (duplicates): {skipped}  |  Total in CRM: {len(total)}")
